### ISSUE TITLE
Odin error

### ISSUE THREAD

**Issue by TheDakk** [mbround18/valheim-docker#114]
$ cargo install --git https://github.com/mbround18/valheim-docker.git --branch main
Updating git repository https://github.com/mbround18/valheim-docker.git
Installing odin v1.1.0 (https://github.com/mbround18/valheim-docker.git?branch=main#d69ba7fb)
Updating crates.io index
Downloaded boxfnonce v0.1.1
Downloaded clap v3.0.0-beta.2
Downloaded serde_json v1.0.62
Downloaded termcolor v1.1.2
Downloaded strsim v0.10.0
Downloaded sysinfo v0.16.3
Downloaded tar v0.4.32
Downloaded syn v1.0.60
Downloaded textwrap v0.12.1
Downloaded xattr v0.2.2
Downloaded version_check v0.9.2
Downloaded unicode-segmentation v1.7.1
Downloaded vec_map v0.8.2
Downloaded ryu v1.0.5
Downloaded serde_derive v1.0.123
Downloaded yaml-rust v0.4.5
Downloaded once_cell v1.5.2
Downloaded proc-macro-error v1.0.4
Downloaded quote v1.0.9
Downloaded proc-macro-error-attr v1.0.4
Downloaded linked-hash-map v0.5.4
Downloaded which v4.0.2
Downloaded thiserror-impl v1.0.23
Downloaded proc-macro2 v1.0.24
Downloaded log v0.4.14
Downloaded lazy_static v1.4.0
Downloaded daemonize v0.4.1
Downloaded libc v0.2.86
Downloaded os_str_bytes v2.4.0
Downloaded hashbrown v0.9.1
Downloaded indexmap v1.6.1
Downloaded heck v0.3.2
Downloaded miniz_oxide v0.4.3
Downloaded itoa v0.4.7
Downloaded adler v0.2.3
Downloaded unicode-xid v0.2.1
Downloaded unicode-width v0.1.8
Downloaded thiserror v1.0.23
Downloaded cfg-if v1.0.0
Downloaded serde v1.0.123
Downloaded doc-comment v0.3.3
Downloaded clap_derive v3.0.0-beta.2
Downloaded flate2 v1.0.20
Downloaded crc32fast v1.2.1
Downloaded filetime v0.2.14
Downloaded autocfg v1.0.1
Downloaded bitflags v1.2.1
Downloaded atty v0.2.14
Downloaded 48 crates (2.3 MB) in 0.36s
Compiling proc-macro2 v1.0.24
Compiling unicode-xid v0.2.1
Compiling libc v0.2.86
error: linker cc not found
|
= note: No such file or directory (os error 2)

error: aborting due to previous error

error: could not compile proc-macro2

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: linker cc not found
|
= note: No such file or directory (os error 2)

error: aborting due to previous error

error: failed to compile odin v1.1.0 (https://github.com/mbround18/valheim-docker.git?branch=main#d69ba7fb), intermediate artifacts can be found at /tmp/cargo-install2Rg1VG

Is this on my end or the repository?

**Comment by mbround18** [comment]
What operating system are you running? you should have build-essentials installed on ubuntu or equivalent to be able to compile locally

**Comment by TheDakk** [comment]
Using Ubuntu 20, was just following your directions here..

https://github.com/mbround18/valheim-docker/blob/main/docs/odin.md

Installed Rust and SteamCMD, guess i'll look for build-essentials :)

**Comment by TheDakk** [comment]
Needed build-essentials to be installed.
