### ISSUE TITLE
[Feature] Add mod support through BepInEx

### ISSUE THREAD

**Issue by rosudrag** [mbround18/valheim-docker#130]
Valheim has a bunch of mods available on NexusMods that work when loaded through the [BepInEx modding framework](https://github.com/BepInEx/BepInEx) / https://www.nexusmods.com/valheim/mods/4 . Downloading them and shoving them on the volumes on this docker doesn't work because it needs extra setup on unix. https://bepinex.github.io/bepinex_docs/master/articles/user_guide/installation/index.html?tabs=tabid-nix

**Comment by rosudrag** [comment]
I've tried adding BepInEx myself but I'm beat... The loader startup scripts just sets up some env variables which can be done in docker-compose with:

- DOORSTOP_ENABLE=TRUE
- DOORSTOP_INVOKE_DLL_PATH=/home/steam/valheim/BepInEx/core/BepInEx.Preloader.dll
- LD_LIBRARY_PATH=/home/steam/valheim/doorstop_libs
- LD_PRELOAD=libdoorstop_x64.so
- DYLD_LIBRARY_PATH=/home/steam/valheim/doorstop_libs
- DYLD_INSERT_LIBRARIES=/home/steam/valheim/doorstop_libs/libdoorstop_x64.so

The library download is at https://builds.bepis.io/projects/bepinex_be and needs copying to the right volume location.

They also mention needing gcc 10+ so a modified image is required with that installed:
RUN echo 'deb http://deb.debian.org/debian testing main' >> /etc/apt/sources.list \
    && apt-get update && apt-get install -y --no-install-recommends -o APT::Immediate-Configure=false gcc g++

It's just crashing with undefined symbol errors:
```ln: symbol lookup error: /home/steam/valheim/doorstop_libs/libdoorstop_x64.so: undefined symbol: dlopen```

**Comment by mbround18** [comment]
Adding belpix support wouldn't be too hard <3

**Comment by mbround18** [comment]
Before I write any code, is BepInEx the only framework used for modding Valheim?

**Comment by rosudrag** [comment]
> Before I write any code, is BepInEx the only framework used for modding Valheim?

Looks to be this way only. Maybe one day the devs will add in official support but why would they even bother when HarmonyX does the job

**Comment by kachunkachunk** [comment]
Just to throw it out there, ValheimPlus also incorporates BePinEx and this seems to load the server component. I'm not certain what the most elegant approach is for handling it, but maybe take a look at their newest 0.8 release for Linux/Unix servers and you can see how it loads/runs, too.

**Comment by mbround18** [comment]
@kachunkachunk done. See #148
