### ISSUE TITLE
[Documentation] Restoring backups

### ISSUE THREAD

**Issue by elliotpryde** [mbround18/valheim-docker#143]
There's currently no explanation of how to restore a backup once it's been taken. I've tried a few different things, but moving the sole `saves` directory within the backup archive to `/home/steam/.config/unity3d/IronGate/Valheim` doesn't seem to have any effect on my character. Any explanation on how this works would be appreciated.

**Comment by mbround18** [comment]
Are you trying to restore your world? or character?
