### ISSUE TITLE
Filesystem Overwrites/Not Copying For Valheim Plus

### ISSUE THREAD

**Issue by nickkeane** [mbround18/valheim-docker#150]
I'm trying to create a custom image to bootstrap ValheimPlus, in anticipation of #148. The Dockerfile looks like this:

> FROM busybox:latest as ValheimPlus
> 
> ENV VPLUS_VERSION "0.8"
> 
> WORKDIR /opt/valheim-plus
> 
> RUN wget https://github.com/nxPublic/ValheimPlus/releases/download/$VPLUS_VERSION/UnixServer.zip \\
>     && unzip UnixServer.zip \\
>     && rm UnixServer.zip
> 
> FROM mbround18/valheim:latest AS Valheim
> 
> RUN mkdir /opt/valheimplus
> RUN mkdir /home/steam/valheim
> 
> COPY --from=ValheimPlus --chmod=755 /opt/valheim-plus /opt/valheimplus/      # this works, files show up
> COPY --from=ValheimPlus --chmod=755 /opt/valheim-plus /home/steam/valheim/      # this doesn't...

Presumably, Odin is overwriting/recreating/doing something weird with the file system there and it's removing my copied files somehow when i start the server, b/c the files i just copied over don't exist in /home/steam/valheim/ as i expect them to when i check the folder in the container. Is Odin deleting and recreating /home/steam/valheim/ whole-cloth?

Is there a way to fix this so i can automate deploying V+? Or another automated method?
I know the quick and dirty solution is to extract the zip manually after filesystem creation, but I like automagic things :3.

**Comment by mbround18** [comment]
Its in the start valheim script, I can add a flag for it

**Comment by mbround18** [comment]
Btw @nickkeane if you want to test out the bepinex feature early, switch your image to `ghcr.io/mbround18/valheim:development-unstable` it should be accessible via github but I am not sure.

**Comment by mbround18** [comment]
It has the switch for force installation 
![image](https://user-images.githubusercontent.com/12646562/108583920-f9e2b080-72f1-11eb-8615-5471c319c5e7.png)

**Comment by nickkeane** [comment]
I'm getting an unauthorized error when referencing the image, not sure if I'm doing it right:

```
Step 5/8 : FROM ghcr.io/mbround18/valheim:development-bepinex AS Valheim
ERROR: Service 'valheim' failed to build : Head https://ghcr.io/v2/mbround18/valheim/manifests/development-bepinex: unauthorized
```

**Comment by mbround18** [comment]
Huh it should be open permissions on that archive, let me try to push to dockerhub

**Comment by mbround18** [comment]
Sweeet looks like someone stopped trying to gain access to my dockerhub,

try just `mbround18/valheim:development-bepinex` which should pull from dockerhub

**Comment by nickkeane** [comment]
When starting the dev image I get this error, the stable image seems to bootstrap steamcmd fine:

> valheim    | [Valheim][steam]: Running Install...
> valheim    | [ODIN][INFO]  - Installing 896660 to /home/steam/valheim
> valheim    | [ODIN][ERROR] - Failed to find steamcmd in path
> valheim    | [ODIN][ERROR] - Checking for script under steam user.
> valheim    | [ODIN][INFO]  - Executing: /home/steam/steamcmd/steamcmd.sh .....
> valheim    | [ODIN][INFO]  - Using steamcmd script at /home/steam/steamcmd/steamcmd.sh
> valheim    | WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
> valheim    | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
> valheim    | [  0%] Checking for available updates...
> valheim    | KeyValues Error: LoadFromBuffer: missing {   (current key: '<!DOCTYPE') in file manifest [offset: 14]
> valheim    | 
> valheim    | /data/src/tier1/KeyValues.cpp (2999) : Assertion Failed: Error while parsing text KeyValues for resource manifest
> valheim    | [----] Verifying installation...
> valheim    | [  0%] Downloading update...
> valheim    | [  0%] Checking for available updates...
> valheim    | KeyValues Error: LoadFromBuffer: missing {   (current key: '<!DOCTYPE') in file manifest [offset: 14]
> valheim    | 
> valheim    | /data/src/tier1/KeyValues.cpp (2999) : Assertion Failed: Error while parsing text KeyValues for resource manifest
> valheim    | [----] !!! Fatal Error: Steamcmd needs to be online to update. Please confirm your network connection and try again.
> valheim    | /data/src/tier0/threadtools.cpp (3658) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x5768cd70/0x0xf7bb2b'
> valheim    | [ODIN][INFO]  - Exited with status code: 254
> valheim    | [Valheim][steam]: Initializing Variables....
> valheim    | [ODIN][ERROR] - Failed to find server executable! Please run `odin install`

**Comment by mbround18** [comment]
Do you have any weird networking preventing the container from reaching outside? Try running docker-compose  down and then docker-compose up

**Comment by nickkeane** [comment]
No it works perfectly fine with the other image (mbround18/valheim:latest). Was something changed with steam or the file system in the dev branch?

**Comment by mbround18** [comment]
Nada nothing was changed in comparison to the steamcmd but i did do some work on the dev branch. Take a look at https://github.com/mbround18/valheim-docker/discussions/149 for the changes that are occuring. Thats also where a few peeps are doing testing as well.
