### ISSUE TITLE
[Feature] Discord Notification through webhook

### ISSUE THREAD

**Issue by mbround18** [mbround18/valheim-docker#152]
Acceptance Criteria:
- Notification class for sending notifications
- Provide  an environment variable to enable/disable
- if present send notifications based on start, stop, and updates.

**Comment by nogweii** [comment]
A variation of this that would also be appreciated is a more generic webhook, so that custom software could be integrated. e.g. A generic webhook could send messages to an HTTP server that can turn around and send to Slack, Matrix, or Pushover.

**Comment by LovecraftianHorror** [comment]
Can you expand a bit on how that would work? Are there exiting solutions that can translate some generic webhook requests to different platforms, or is that something we would need to work on?

**Comment by mbround18** [comment]
I could throw together something like that  where it sends a post with a a documented request body? And then add a mutation layer for discord specific events. Thoughts?

**Comment by LovecraftianHorror** [comment]
Would that be within `odin` or a separate service? I think a web server that can be spawned with options to relay the messages to slack, discord, etc. could work well, but if there is a pre-existing service that already basically does that then it would be nice to leverage too.

**Comment by mbround18** [comment]
This would be an Odin option using ureq to post to an outgoing webhook.

Typical infrastructure for something like this would be 

Odin -> post request -> webhook -> an independent webserver ingests it and sends it to where it needs to go.

In the case of discord or similar chat platforms it could be simplified by sending directly to discord through their interface for a webhook which is why I suggested the mutation for discord etc. I am working on a demo of this right now :)

**Comment by mbround18** [comment]
![image](https://user-images.githubusercontent.com/12646562/108796714-3c98c880-753e-11eb-8962-5cd51daa024d.png)
