### ISSUE TITLE
[Enhancement] Improve docker image build times

### ISSUE THREAD

**Issue by LovecraftianHorror** [mbround18/valheim-docker#153]
# Cache odin compilation with `cargo chef`

I'm sure you'be noticed, but currently there is a full clean compile each time the `odin` image is built. `cargo chef` helps fix this issue by doing some magic behind the scenes to enable docker to cache the dependencies and all that. I've personally been using it already locally to help with build times when testing. This is the custom dockerfile I've been using for odin:

```dockerfile
FROM lukemathwalker/cargo-chef as planner
WORKDIR /data/odin
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM lukemathwalker/cargo-chef as cacher
WORKDIR /data/odin
COPY --from=planner /data/odin/recipe.json recipe.json
RUN cargo chef cook --release --recipe-path recipe.json

FROM rust as builder
WORKDIR /data/odin
COPY . .
# Copy over the cached dependencies
COPY --from=cacher /data/odin/target target
COPY --from=cacher $CARGO_HOME $CARGO_HOME
RUN cargo build --release --bin odin

FROM rust as runtime
WORKDIR /data/odin
COPY --from=builder /data/odin/target/release/odin /usr/local/bin
ENTRYPOINT ["/usr/local/bin/odin"]
CMD ["--version"]
```

This is basically a barely modified version of the example in `cargo chef`'s README.

# Cache the build info with github actions

Now the next step would be to cache the files so that they can actually be used to speed up CI. It looks like [this action](https://github.com/marketplace/actions/docker-layer-caching) can help with that, but I honestly haven't done any docker image building in CI before so there's possibly better.

**Comment by mbround18** [comment]
Ohh my, that does speed up builds considerably :D
