### ISSUE TITLE
Cant find server ingame

### ISSUE THREAD

**Issue by findanish** [mbround18/valheim-docker#154]
Hi there,

I have PUBLIC=1 set but none of my friends are able to see the server ingame or steam. They can however add the server by ip from steam and ingame but not by name. Is it because i have spaces in the server name?

**Comment by mbround18** [comment]
Nada this is a limitation on Valheims server list side. They limit the amount of servers visible, checkout the discussion on the subject here: https://github.com/mbround18/valheim-docker/discussions/51
