### ISSUE TITLE
[Enhancement] New Env Variable for Valheim Plus 0.8.5

### ISSUE THREAD

**Issue by nickkeane** [mbround18/valheim-docker#166]
ValheimPlus 0.8.5 adds a new env variable, DOORSTOP_CORLIB_OVERRIDE_PATH=./unstripped_corlib

Without it the following error occured:

valheim    | ==> /home/steam/valheim/logs/valheim_server.err <==
valheim    |
valheim    | Unhandled Exception:
valheim    | System.MissingMethodException: void System.IO.File.WriteAllText(string,string)
valheim    | [ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: void System.IO.File.WriteAllText(string,string)

Manually adding the env var fixed this issue.

**Comment by mbround18** [comment]
Not a bug, an enhancement. They just released this feature as of 9 hours ago. 

Ill take a look at it.
