### ISSUE TITLE
Auto update on startup doesn't run

### ISSUE THREAD

**Issue by ragingdave** [mbround18/valheim-docker#206]
Title says it all, the auto update never runs. This looks to be an issue with both the conditional logic since the auto update would only run if the first condition is false, but it's never hitting that if you mount the server volume.

Also a syntax error in the start script:
Logs say:
```
[Valheim][steam]: Running Install...
/home/steam/scripts/start_valheim.sh: line 48: [: missing `]'
[Valheim][steam]: Skipping install process, looks like valheim_server is already installed :)
[Valheim][steam]: Initializing Variables....
```

**Comment by dkurzaj** [comment]
Seems to be fixed by https://github.com/mbround18/valheim-docker/pull/204 but not yet pushed to docker hub.

**Comment by LovecraftianHorror** [comment]
Yup I believe it should work right after this latest image is published. I'm pretty sure the conditional logic is right now, but I'm also very sleep deprived currently so the more people double checking me, the better 😅

**Comment by dkurzaj** [comment]
Yep, works like a charm for me!
