### ISSUE TITLE
Discord url does not allow discordapp.com

### ISSUE THREAD

**Issue by pfrumau** [mbround18/valheim-docker#211]
Hi, great work! 

I ran into an issue with the webhook, where it requires discord.com as a `WEBHOOK_URL`. however, when i copy paste the webhook url from the discord app, it gives me discordapp.com. i guess its the same backend. However the error is not very informative:

```
odin notify -r 'test'
```
gives me:
```
 Request failed! 400 Bad Request, {"message": "Cannot send an empty message", "code": 50006}
```
because the is_discord_message returns false.

suggested update `notifications/discord.rs`
```
const DISCORD_WEBHOOK_BASE: &str = "https://discord.com/api/webhooks";
const DISCORD_WEBHOOK_BASE_ALT: &str = "https://discordapp.com/api/webhooks";

impl From<EventStatus> for Color {
  fn from(event: EventStatus) -> Self {
    use EventStatus::{Failed, Successful};
    match event {
      Successful => Self::Success,
      Failed => Self::Failure,
      _ => Self::Generic,
    }
  }
}

pub fn is_discord_webhook(webhook_url: &str) -> bool {
  webhook_url.starts_with(DISCORD_WEBHOOK_BASE) || webhook_url.starts_with(DISCORD_WEBHOOK_BASE_ALT)
}
```

**Comment by LovecraftianHorror** [comment]
That's a good catch! Do you know of any other common bases for discord webhooks, like if http can also be used instead of https? I wasn't able to find any listings from my little bit of searching.

**Comment by pfrumau** [comment]
no idea, I guess these two will be about it.

Another option would be to use a regex, something like (you can try at regexr.com)
```
(http.*discord.*\/api\/webhooks.*)
```

but i'm new to rust so dont know how to code that (https://docs.rs/regex/1.4.3/regex/)

ps.
Another issue i had was when i wrapped the api url in quotes it failed because the string started with "
I guess changing the documentation (docker-compose) to remove the quotes will be sufficient to catch that.
