### ISSUE TITLE
Getting Two Discord Server Stop Notifications On Container Restart

### ISSUE THREAD

**Issue by bforbis** [mbround18/valheim-docker#214]
If you restart the container while having a `WEBHOOK_URL` and `UPDATE_ON_STARTUP` set, the following happens:

1. Webhook notification that server has stopped (triggered from container stop)
2. On start, server launches into `auto_update.sh` script
    - auto_update will first call `odin stop`
    - odin will send a notification that the server has stopped again

I guess odin should check if the server is already stopped before sending the server stopped notification. Alternatively, an option command could be passed to `odin stop` to disable the webhook when called from within the `UPDATE_ON_STARTUP` block

**Comment by pwlgrzs** [comment]
I can confirm, getting same doubled notifications.
![image](https://user-images.githubusercontent.com/7893951/109396326-3c7b3d00-7931-11eb-951c-40ee9c98cc7f.png)

**Comment by mbround18** [comment]
This is probably related to #213 which would start the server twice. The pull request #213 should fix that :P keep an eye on the release channel for when it is live.

**Comment by mbround18** [comment]
Can you confirm this is fixed? I am out of cell service most of the day and cannot test

**Comment by pwlgrzs** [comment]
Just pulled newest image, all looks good now.

![image](https://user-images.githubusercontent.com/7893951/109403696-461b9980-795f-11eb-8b9e-ca60bc14bd5c.png)
