### ISSUE TITLE
Dockerfile / docker-compose usage

### ISSUE THREAD

**Issue by Webrow** [mbround18/valheim-docker#22]
Hey, Thank you for the work put into this project. 
I build the Dockerfile into an image, and started it with docker-compose up -d. 
Server starts nicely, but there is no way for me to "find" the server. 
The readme states a lot of usage regarding odin, but as far as I can see when I use the docker-compose file the init + entry should start the server perfectly and the server should start running on the specified port no?

Is there anyway from inside the container to retrieve information regarding the running server so I can debug something?

**Comment by mbround18** [comment]
Yes the server should initialize on the specified port, are you looking to find the server in the in game server browser?

**Comment by Webrow** [comment]
No currently using the steam server browser. added the ip + port to make sure it should list. 
Whenever I start the container (regardless of the port set in the docker-compose it always adds a udp 2456 entry in my iptables) Nevertheless on all 3 ports, nor the one specified a game can be found

**Comment by mbround18** [comment]
Are you doing this from your local machine or a VPS? I always test on an ubuntu VPS and I had to ensure my firewall allowed access to those ports.

**Comment by Webrow** [comment]
This is a linux machine where as far as I know all the port rules have been opened. whenever I use tail on the output this it never reaches Gameserver connected 

`
Unloading 490 unused Assets to reduce memory usage. Loaded Objects now: 86220.
Total: 70.936903 ms (FindLiveObjects: 4.447402 ms CreateObjectMapping: 10.294278 ms MarkObjects: 51.873984 ms  DeleteObjects: 4.316696 ms)

02/09/2021 22:28:52: Zonesystem Start 266

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

02/09/2021 22:28:53: DungeonDB Start 266

(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)
`

**Comment by Webrow** [comment]
@mbround18 it worked out for me finally, when specifying a port, the server will always start at port + 1, so 2456 became 2457, at that port I was able to connect.

**Comment by mbround18** [comment]
Ahh yeah, thats just how the server works 🤷 I am glad its online <3
