### ISSUE TITLE
Setting UID / PID can have big issues on shared servers

### ISSUE THREAD

**Issue by Webrow** [mbround18/valheim-docker#23]
Hey, 

Setting UID / PID can have major issues (in my case all files of the server are owned by another user, if you are not able to sudo you will be unable to chown the files. Might it be an idea to introduce a user created in the alpine image and from there connect it. Yes itll cause write / read issues during copying of savegames into temp, but isnt that how it is supposed to work (or maybe use whoami to determine who is building the Dockerfile instead of hardcoding it?)

**Comment by MattPark** [comment]
It's fixed in latest.  See #16.  You can set to whatever you need to using PGID/PUID env variable

**Comment by Webrow** [comment]
Hey Matt, its not regarding the matter that its fixed, just that it defaults to 1000. 1000 is not always your own user, and knowing it later on can cause bigger issues. (I assume 1000 was chosen cause often its the first user). Nevertheless its a nitpick. Ill close it!

**Comment by MattPark** [comment]
Yeah I mean I see your point though.  Like ideal default should be the result of `id -u` and `id -g` probably ... not a huge deal since this fix gives everyone the option whereas option was missing before.

**Comment by Webrow** [comment]
Agreed

Op wo 10 feb. 2021 00:06 schreef Matt Park <notifications@github.com>:
