### ISSUE TITLE
Allowing world name in backup file

### ISSUE THREAD

**Issue by devsi** [mbround18/valheim-docker#232]
I was switching between worlds from `saves/worlds/` on my server and noticed that the backups don't reflect the world change if the world alters. This makes it impossible to tell which backup file belongs to which world.

Could the backup file use also contain the world name to avoid this problem?

Alternatively, could the filename format be specified as an ENV VAR in docker-compose so we have custom control over the name?

**Comment by mbround18** [comment]
Backups are per your whole save folder and not per world. Thus, if you are switching world names its best to check the `tar.gz` file for the world you wish to restore. This is because many servers utilize multiple worlds.
