### ISSUE TITLE
[Enhancement]: Ability to change Discord message contexts

### ISSUE THREAD

**Issue by mbround18** [mbround18/valheim-docker#237]
> Thanks will check it out! Unrelated, but is there a way to change the discord notification colors? Like red if it’s stopped?
> _Originally posted by @TheDakk in https://github.com/mbround18/valheim-docker/discussions/228#discussioncomment-419354_

Acceptance Criteria:

* User can change color of Discord notification
* User can change title of Discord notification
* User can change body of Discord notification

**Comment by RyanKeys** [comment]
Discord can handle code snippets, so in this instance could we use diff snippets for the server status, and something like json for generalized alerts?

For example:
(On Discord only the text is colored)
```diff
+ <START MESSAGE HERE>
```
```diff
- <STOP MESSAGE HERE>
```
```json
"<SERVER MESSAGE HERE>"
```

**Comment by mbround18** [comment]
I have been debating on how to handle this. I was thinking of doing a template for it with a consistent message.

**Comment by mbround18** [comment]
I am to start tackling this this coming ~Wednesday, i think the template message would be best after a little testing.

**Comment by mbround18** [comment]
@RyanKeys this is upgraded in 1.4.0

**Comment by mbround18** [comment]
https://github.com/mbround18/valheim-docker/blob/main/docs/webhooks.md
