### ISSUE TITLE
Allow changing the "public" variable

### ISSUE THREAD

**Issue by broizter** [mbround18/valheim-docker#24]
When you launch the server software, there's a parameter called public that you can give either a value of 0 or 1. This is helpful if you wanna use the permittedlist.txt file to keep a whitelist of users that can connect. Would be awesome if this parameter could be changed through one of the environment variables similar to how the server name, password and so on can be changed.

It's this line I want to be able to change: https://github.com/mbround18/valheim-docker/blob/27a01f73b028d798b0d550e9de53567d2e7145fb/src/files/start_server_rusty.rs#L18

**Comment by mbround18** [comment]
I can take a look at adding that :)

**Comment by mbround18** [comment]
I have a PR up for this, I am going to crash since it is 1am for me. Ill review my updates tomorrow and merge them after retesting :) Feel free to take a gander at the changes #29

**Comment by mbround18** [comment]
Changes look good <3
