### ISSUE TITLE
[Bug] Wrong Discord message on start after automatic_update

### ISSUE THREAD

**Issue by AlexSoder** [mbround18/valheim-docker#246]
The discord webhook sends two Stop messages and no start message after automatic restart due to automatic_update=1.
The second message says "Stop Successful" which  leads me to believe it is supposed to say "Start Successful".
<img width="409" alt="Screenshot 2021-03-04 at 09 04 45" src="https://user-images.githubusercontent.com/3648302/109931204-d728a280-7cc8-11eb-8dd7-bf182d33336c.png">

**Comment by LovecraftianHorror** [comment]
Moving this over to discussions with the other questions/bugs (#61)
