### ISSUE TITLE
No "Start Successful" Discord notification on auto-update

### ISSUE THREAD

**Issue by pwlgrzs** [mbround18/valheim-docker#255]
Server stops at 5AM for auto-update following these variables:
  -e AUTO_UPDATE=1
  -e AUTO_UPDATE_SCHEDULE="0 5 * * *" 

Our Discord gets 2 notifications:

![image](https://user-images.githubusercontent.com/7893951/110086228-66e65380-7d92-11eb-879c-4ee6f192250a.png)

but we do not receive Start Successful message.

**Comment by LovecraftianHorror** [comment]
Can you post a (censored) docker compose file (or equivalent), along with a server log and when you last pulled the image. This has been a bug that seems to have hit a few people, but I still haven't been able to reproduce.

Don't list the full webhook url you pass in, but knowing if it's discord or discordapp would be nice too.

**Comment by pwlgrzs** [comment]
`#!/bin/bash

docker stop valheim
docker rm valheim
docker pull mbround18/valheim:latest

docker run -d \
  --name valheim \
  -p 2456:2456/udp \
  -p 2457:2457/udp \
  -p 2458:2458/udp \
  -v /local/valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim \
  -v /local/valheim/server:/home/steam/valheim \
  -v /local/valheim/backup:/home/steam/backups \
  -e PUBLIC=1 \
  -e PORT=2456 \
  -e NAME="="*****" " \
  -e PASSWORD="*****" \
  -e TZ=Europe/Warsaw \
  -e WORLD=World \
  -e AUTO_UPDATE=1 \
  -e AUTO_UPDATE_SCHEDULE="0 5 * * *" \
  -e UPDATE_ON_STARTUP=1 \
  -e AUTO_BACKUP=1 \
  -e AUTO_BACKUP_SCHEDULE="*/15 * * * *" \
  -e AUTO_BACKUP_REMOVE_OLD=1 \
  -e AUTO_BACKUP_DAYS_TO_LIVE=3 \
  -e AUTO_BACKUP_ON_UPDATE=1 \
  -e AUTO_BACKUP_ON_SHUTDOWN=1 \
  -e WEBHOOK_URL=https://discord.com/api/webhooks/********** \
  -e WEBHOOK_BROADCAST_MESSAGE="HEHE VALHEIM" \
  --restart=always \
  mbround18/valheim`
  
  Image pulled: 2021-03-02 10:03:56
 Log:
[valheim_server.log](https://github.com/mbround18/valheim-docker/files/6089095/valheim_server.log)

**Comment by pwlgrzs** [comment]
Also, message for auto-update says: "Notification From: Your Valheim Server" while if I do odin stop it will say "Notification From: ACTUAL SERVER NAME".

**Comment by LovecraftianHorror** [comment]
Does stopping and starting the container send out the messages correctly. I would pull the latest image, I think there was some work towards fixing this issue earlier today.

> Also, message for auto-update says: "Notification From: Your Valheim Server" while if I do odin stop it will say "Notification From: ACTUAL SERVER NAME".

This is a known issue. I'll go ahead and push out a fix for this.

**Comment by pwlgrzs** [comment]
I just pulled newest image but obviously we gotta wait till 5AM to see.

**Comment by LovecraftianHorror** [comment]
No worries, gives me time to stall :D

In the meantime I went ahead and opened a pull request to fix the name not getting read for auto updates (#256)

![image](https://user-images.githubusercontent.com/30302768/110090303-215f6180-7d65-11eb-88f5-a38cb0aaf679.png)
