### ISSUE TITLE
Can you make basic guide?

### ISSUE THREAD

**Issue by gunnrcrakr** [mbround18/valheim-docker#26]
I never use Docker before, I want to launch server for my friends via DigitalOcean, Can you make Quickstart Basic (Noob) Guide ?

**Comment by mbround18** [comment]
Absolutely!

**Comment by gunnrcrakr** [comment]
> Absolutely! This repo technically has two tools inside of it, if you have a VPS or just a server you dont have to do docker if you want to install and run it the traditional way. (Thats what the Odin tool is about) But I can write up a docker guide in the discussions :)

Please write up docker guide 👯

**Comment by mbround18** [comment]
Let me know if I need to add more details <3 see discussion #28
