### ISSUE TITLE
[Enhancement] MODS environment variable

### ISSUE THREAD

**Issue by mbround18** [mbround18/valheim-docker#272]
Acceptance Criteria:
* `installmod` odin command.
* Ability to detect if the mod is a `dll` or valheim plus.
* staging the mod information.
* installed mods configuration file.

**Comment by neoKushan** [comment]
Thunderstone has a good documented API we could probably take advantage of to pull mods in https://valheim.thunderstore.io/api/docs/

**Comment by mbround18** [comment]
> Thunderstone has a good documented API we could probably take advantage of to pull mods in https://valheim.thunderstore.io/api/docs/ 

A good amount of these mods are windows client only tho. Thoughts on how we could get peeps to not install those than get confuzzled?

**Comment by mbround18** [comment]
Also, I already have the nexus, unfortunately nexus is paywalled. If you want to install any nexus mods you will have to use their premium *rolls eyes*

**Comment by neoKushan** [comment]
It's a good question, there doesn't seem to be any kind of tags to indicate server vs client even on nexus mods which is a bit of a bugger as that would be a natural way to filter.

The bigger elephant in the room is that ValheimPlus is one of the few not on Thunderstone (though I believe most of the mods are compatible with it). 

I guess it's a case of how helpful we want to be. We could theoretically do all the heavy lifting of installing bepinex/ValheimPlus (Maybe this is a top-level decision as to which "version" of bepinex you want, vanilla or ValheimPlus), then pull, unzip and install any additional mods from some kind of config file to keep it nice and easy. Or we could just install ValheimPlus and let users copy the right DLLs to the right folders.

**Comment by mbround18** [comment]
a lot of other docker repos do that heavy lifting but honestly they are hard coding that. I am taking the approach of doing an analysis on any zip downloaded and extracting where needed. Similar to how minecraft does it :) that way it can be agnostic of what url you add and all you have to do is keep track of which link is in which order. (mod loader list) Than if you want a new version or an older version just change the link to match.

**Comment by ouvoun** [comment]
> The bigger elephant in the room is that ValheimPlus is one of the few not on Thunderstone (though I believe most of the mods are compatible with it).

Requests for them to join Thunderstore seem to be pretty much ignored. Frankly I'm not sure why. Regardless, it's an excellent mod repository with a lovely client to boot (r2modman). I've used it extensively for Risk of Rain and it's been quite nice.

Unfortunately as you've discovered, @mbround18, there isn't metadata describing platform support. In my humble opinion that responsibility should just fall on the users to validate whether their desired mod is supported within this container.

I love the idea of an environmental variable for this, and will watch this eagerly for progress. :)

**Comment by mbround18** [comment]
> I love the idea of an environmental variable for this, and will watch this eagerly for progress. :)

Its getting there <3 the hurtle i am at now is how do you differentiate between a mod that needs to be extracted to the root of the server dir or extracted into the bepinex/plugins directory?

![image](https://user-images.githubusercontent.com/12646562/110415962-1b60cd80-8050-11eb-9fd2-6af51804f594.png)

**Comment by neoKushan** [comment]
Can you go off of the presence of a `bepinex/plugin` tree? Presumably that folder combination would imply the .zip must be extracted to a particular root folder (which you can align based off of where the `bepinex` folder is), whereas the absence of one you can probably assume it just goes into `bepinex/plugins`.

**Comment by mbround18** [comment]
@neoKushan sadly not all mod developers do that :P some create it in a sub folder of various names and others include various additional files to be extracted in other locations. 

It might be, I just need to throw up a guide on whats an acceptable zip file to install.

**Comment by ouvoun** [comment]
@mbround18 I realize a single ENV variable doesn't give you a lot of room to play with, but I wonder how feasible it'd be to define the structure of each mod?

So for each mod to install, you'd list:
- The zip URL
- The dll location within the zip file (e.g. `BepInEx/plugins/ValheimPlus.dll`)
- Config locations within the zip file (e.g. `BepInEx/config/valheim_plus.cfg`)

This would work for Valheim Plus, for example, as long as BepInEx can be installed automatically if mods are enabled.

With that said, that's a little bit janky. It'd be nicer if you could just specify a Thunderstore package and have it use the latest version instead. I don't know enough about the Thunderstore manifest to know if that's possible though. It doesn't seem to have information defined about the top-level vs nested structure, so maybe you'd be in the same situation you are in now?

**Comment by neoKushan** [comment]
Thunderstone does have the mod pack details on its github: https://github.com/thunderstore-io/Thunderstore though it doesn't list specifics for valheim. It does list dependencies though, which is helpful. 

Looking at a selection of mods, there's no consistency to how they're packaged and nothing in the metadata to help. It seems bepinex will recursively search the plugins folder for additional plugins to load though, so if I had to guess you can just dump everything into the plugins folder and it'll work. Seems messy though.

It'd probably make sense to make that entirely ephemeral , that is to start from a clean plugins folder and dump the mods in when the container starts.

**Comment by mbround18** [comment]
Currently, i am taking a non atomic approach. If you want to remove mods its up to the user to clean up files remaining on the system. As for mods I am currently testing with the following zip files: 

ValheimPlus: https://github.com/valheimPlus/ValheimPlus/releases/download/0.9.4/UnixServer.zip
BepInEx from Thunderstone: https://cdn.thunderstore.io/live/repository/packages/denikson-BepInExPack_Valheim-5.4.800.zip

**Comment by neoKushan** [comment]
I'm sure you've checked this already, but it's worth knowing that the contents of both of those are almost identical, just ValheimPlus has the `ValheimPlus.dll` and `Valheim.DisplayBepInExInfo.dll` DLLs in the plugins folder and `valheim_plus.cfg` in the config folder.

The `start_game_bepinex.sh` / `start_server_bepinex.sh` files are different but I don't think there's anything importantly different about those files.

Going by the minecraft example earlier that you've been going off of, perhaps this is really just a different "type" of game server?

Nice simple ENV variable to decide which base to start from:

`TYPE=Vanilla` (default ofc)
`TYPE=BepInEx`
`TYPE=ValheimPlus`

Then all the user needs to do is add their additional mods however they want.

**Comment by mbround18** [comment]
Thats not a bad idea :)

**Comment by ouvoun** [comment]
> Nice simple ENV variable to decide which base to start from:
> 
> TYPE=Vanilla (default ofc)
> TYPE=BepInEx
> TYPE=ValheimPlus
> 
> Then all the user needs to do is add their additional mods however they want.

I like this idea, but the downside is that it wouldn’t be able to support automatic updates for non-V+ mods.

**Comment by mbround18** [comment]
The other issue is, there is no reliable way to get valheim plus updates without hitting the github api and that has a pull rate that with the amount of people who use this container would surpass.

**Comment by ouvoun** [comment]
As long as V+ isn't bundled with the container, each instance should be fine with hitting the releases endpoint without hitting any sort of limit, right? I assume the API limits are per-IP rather than per-repo.
 
`https://api.github.com/repos/valheimPlus/ValheimPlus/releases/latest`

**Comment by mbround18** [comment]
Good idea, i have it pulling the latest zip file with 
```sh
curl https://api.github.com/repos/valheimPlus/ValheimPlus/releases/latest | jq -r '.assets[] | select(.name=="UnixServer.zip") | .browser_download_url'
```

**Comment by mbround18** [comment]
Hey @ouvoun I am going to be tossing up a dev image in a little. Are you interested in giving it a whirl?

**Comment by ouvoun** [comment]
@mbround18 Sure, happy to give it a spin!

**Comment by mbround18** [comment]
Alrighty :) Its ready <3 
```txt
Dev Image: mbround18/valheim-odin:development-mods
New Environment Variables: 
TYPE=Vanilla | ValheimPlus | BepInEx
MODS= List of mods separated by command new line
```


Example docker-compose: 
```yml
version: "3"
services:
  valheim:
    image: mbround18/valheim:development-mods
    environment:
      - PORT=2456
      - NAME="Creative Update"
      - PASSWORD="12345"
      - TZ=America/Los_Angeles
      - DEBUG_MODE=1
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="*/5 * * * *"
      - UPDATE_ON_STARTUP=0
      - TYPE=ValheimPlus
      - "MODS=
          https://cdn.thunderstore.io/live/repository/packages/abearcodes-SimpleRecycling-0.0.10.zip,
          https://cdn.thunderstore.io/live/repository/packages/abearcodes-CraftingWithContainers-1.0.9.zip
        "
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    volumes:
    - ./tmp/saves:/home/steam/.config/unity3d/IronGate/Valheim
    - ./tmp/server:/home/steam/valheim
    - ./tmp/backups:/home/steam/backups
```

**Comment by mbround18** [comment]
Hey @ouvoun if you nest the plugin does it load just fine? 0.o

**Comment by ouvoun** [comment]
@mbround18 Seems to, yeah! Maybe check yourself too just in case. :)

**Comment by mbround18** [comment]
[New update is out where it extracts it to a sub folder](https://hub.docker.com/layers/mbround18/valheim/development-mods/images/sha256-dc9ff37b2e0e24fdbdffbe1b23d512f5e67adc7fa36c00d4b721c15db87bf90e?context=explore)

**Comment by ouvoun** [comment]
@mbround18 Nice, works great. Also tried it with a [mod ](https://valheim.thunderstore.io/package/Zinal001/Server_Messages/) that has a nested "plugins" folder structure, and it seemed to load fine.

**Comment by mbround18** [comment]
Lol true, for now tho it should be all good. I pushed a new update to the image which should fix the cron jobs :P (which i broke in the last push)

**Comment by ouvoun** [comment]
@mbround18 One quick suggestion for a future improvement. Thunderstore has a nice API to get the latest version for a mod. For example, hitting this API:
`https://valheim.thunderstore.io/api/experimental/package/abearcodes/SimpleRecycling/`

Gives you this response:
```
{
  "namespace": "abearcodes",
  "name": "SimpleRecycling",
  "full_name": "abearcodes-SimpleRecycling",
  "owner": "abearcodes",
  "package_url": "https://valheim.thunderstore.io/package/abearcodes/SimpleRecycling/",
  "date_created": "2021-03-01T02:16:02.136885Z",
  "date_updated": "2021-03-09T22:52:48.070132Z",
  "rating_score": 170,
  "is_pinned": false,
  "is_deprecated": false,
  "total_downloads": 128588,
  "latest": {
    "namespace": "abearcodes",
    "name": "SimpleRecycling",
    "version_number": "0.0.10",
    "full_name": "abearcodes-SimpleRecycling-0.0.10",
    "description": "Adds a tab to the crafting station that recycles (uncrafts) items from player inventory",
    "icon": "https://cdn.thunderstore.io/live/repository/icons/abearcodes-SimpleRecycling-0.0.10.png",
    "dependencies": [
      "denikson-BepInExPack_Valheim-5.4.600"
    ],
    "download_url": "https://valheim.thunderstore.io/package/download/abearcodes/SimpleRecycling/0.0.10/",
    "downloads": 501,
    "date_created": "2021-03-09T22:52:47.760653Z",
    "website_url": "https://github.com/abearcodes/Valheim",
    "is_active": true
  },
  "community_listings": [
    {
      "has_nsfw_content": false,
      "categories": [],
      "community": "valheim"
    }
  ]
}
```

It would be neat if mods could be supplied as versioned full names instead of the direct URL, so auto updates could work. For example:

```
namespace-modname@latest
namespace2-anothermod@0.0.1
```

**Comment by mbround18** [comment]
Ill wait until they solidify their api, for now you can also just copy the manual download link :P 

![image](https://user-images.githubusercontent.com/12646562/110595465-4411c180-813b-11eb-81da-fed4ce618e1a.png)

I added code last push to follow redirects :P

**Comment by ouvoun** [comment]
Fair enough! By the way, I see in your PR that the URL for BepInEx is hardcoded which _might_ cause some issues down the road once it updates and breaks dependencies. :) Future problems I suppose lol.

**Comment by mbround18** [comment]
Thats an easy enough change :P for just one mod its no biggie :p check out my latest push

**Comment by neoKushan** [comment]
You're a machine @mbround18 !

**Comment by spannerman79** [comment]
This looks **very** interesting.

One thing that I don't know if its been mentioned yet or not - because of how _easy_ it is to cheat as Valheim is not an authrotive server model the only Anti Cheat I've came across is [this one](https://www.nexusmods.com/valheim/mods/269).  Down side is that it needs this package of [BepInEx Full](https://valheim.thunderstore.io/package/1F31A/BepInEx_Valheim_Full/). 

I _did_ try to see about giving that Full BepInEx package a spin but I need more sleep as I must be missing something simple.

**Comment by mbround18** [comment]
> This looks **very** interesting.
> 
> One thing that I don't know if its been mentioned yet or not - because of how _easy_ it is to cheat as Valheim is not an authoritative server model the only Anti Cheat I've came across is [this one](https://www.nexusmods.com/valheim/mods/269). Down side is that it needs this package of [BepInEx Full](https://valheim.thunderstore.io/package/1F31A/BepInEx_Valheim_Full/) to be on the server. Doesn't need to be on client side for either.
> 
> I _did_ try to see about giving that Full BepInEx package a spin but I need more sleep as I must be missing something simple as Odin doesn't seem to pick it up even after setting the correct locations for the env vars.

Odin looks for doorstop to be in the root of the server as thats most common. Additionally it wont recognize this full package  and you would have to mess with some env vars to get it to extract properly. Good call out tho! whats the tru difference between 

This: 
https://valheim.thunderstore.io/package/1F31A/BepInEx_Valheim_Full/


And this: 
https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/

???

**Comment by spannerman79** [comment]
Well I managed to come across https://valheim.thunderstore.io/package/1F31A/BepInEx_Valheim_Full_Updater/#reasoning:~:text=Reasoning,GitHub%20if%20you%20encounter%20any%20problems @mbround18 

Interesting read as to why.  And if its the actual cause then I would tend towards former over the latter

**Comment by mbround18** [comment]
done, I have a commit which supports this package now. Will toss it up in a bit.

**Comment by mbround18** [comment]
The change should be live on the `mbround18/valheim-odin:development-mods` latest push :P

**Comment by spannerman79** [comment]
I did some testing and here is some feedback for you.

First of all - great work!

Now the nitty gritty
---------
My compose is the following;
```yml
version: "3"
services:
  valheim:
    image: mbround18/valheim:development-mods
    environment:
      - PORT=2456
      - NAME="Creative Update"
      - PASSWORD="12345"
      - TZ=Australia/Sydney
      - DEBUG_MODE=1
      - AUTO_UPDATE=1
      - AUTO_UPDATE_SCHEDULE="*/5 * * * *"
      - UPDATE_ON_STARTUP=0
      - TYPE=BepInEx
      - "MODS=
          https://cdn.thunderstore.io/live/repository/packages/1F31A-BepInEx_Valheim_Full_Updater-1.0.2.zip
        "
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    volumes:
      - /share/Valheim_Docker/testing/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - /share/Valheim_Docker/testing/server:/home/steam/valheim
      - /share/Valheim_Docker/testing/backups:/home/steam/backups
```
The `TYPE` env var will fail when using `ValheimPlus` and BepInEx_Valheim_Full_Updater - could be their side too not picking up on the pack difference between ValheimPlus and the standard BepInEx package.

Also while Odin will state that BepInEx doesn't listen to SIGINT if you run the container with Console Interactive & TTY (-i -t) (using portainer - i know lazy but meh) attaching and doing a `Ctrl+c` will send SIGINT and the server will terminate correctly without needing to join the server (as admin) and in console doing a `save`.

To automate adding V+ to a setup like this(old fashoned/non automated way);

```
unzip -j "/path/to/UnixServer.zip" "/BepInEx/plugins/ValheimPlus.dll" -d "/path/to/server/BepInEx/plugins/ValheimPlus.dll"
unzip -j "/path/to/UnixServer.zip" "/BepInEx/config/BepInEx.cfg" -d "/path/to/server/BepInEx/config/BepInEx.cfg"
```

**Comment by mbround18** [comment]
YOu can just use type set to `BepInExFull` 0.o

**Comment by spannerman79** [comment]
> Than add valheim plus to your mods variable, errm that wont work doe. I would say ValheimPlus is incompatible with running BepInEx Full unless you want to manually copy the files. This gets kind of into the trenches with mods how there is no standard way of doing things.

Your telling me.

They _use_ to have just the plugin only over on the nexus.  Looks like its been hidden.  Maybe too many people had NFI what they were doing :shrug:

**Comment by spannerman79** [comment]
[From 0.9.5 onwards](https://github.com/valheimPlus/ValheimPlus/issues/324#issuecomment-797271856) V+ will have a compatable package @mbround18

**Comment by mbround18** [comment]
> [From 0.9.5 onwards](https://github.com/valheimPlus/ValheimPlus/issues/324#issuecomment-797271856) V+ will have a compatable package @mbround18 

Dannng!! Nice!!! I saw your issue you posted, thank you for being such a go getter for this ❤️

**Comment by ouvoun** [comment]
Looks like 0.9.5 was released. Looks like `valheim_plus.cfg` and `ValheimPlus.dll` are both listed as separate files that'd need to be installed. I guess they'd need to be copied to the config and plugins folders, respectively.

Maybe if we remind them gently enough times that Thunderstore would be a huge boon for everyone they'll do it and make it easier for everyone. At this point I can't help but think their lack of doing so is related to monetization.

**Comment by mbround18** [comment]
> Looks like 0.9.5 was released. `valheim_plus.cfg` and `ValheimPlus.dll` are both listed as separate files that'd need to be installed. I guess they'd need to be copied to the config and plugins folders, respectively.
> 
> Maybe if we remind them gently enough times that Thunderstore would be a huge boon for everyone they'll do it and make it easier for everyone. At this point I can't help but think their lack of doing so is related to monetization.

Nahhh it should generate the config on launch :P so extracting the config to the config folder is extra work ;)

**Comment by ouvoun** [comment]
> Nahhh it should generate the config on launch :P so extracting the config to the config folder is extra work ;)

FWIW I tried that in one of the past releases and it failed to launch due to a missing config, so if they've fixed it then that would be great. :)

**Comment by spannerman79** [comment]
> it should generate the config on launch

It does, but it would be "easier" for first time setups.  After that yes, updating V+ will be needed as the config would need to be modified.

_if only Valheim had a smart config uptate/checker built in.  I do miss how when botania (minecraft mod) updated it only removed config coptions when they didn't apply and it appended the config file with any new config options._

**Comment by mbround18** [comment]
@ouvoun and @spannerman79 I just pushed a fix for this :) 

```
- TYPE=BepInExFull

- "MODS=
       https://github.com/valheimPlus/ValheimPlus/releases/download/0.9.5.5/ValheimPlus.dll,
       https://github.com/valheimPlus/ValheimPlus/releases/download/0.9.5.5/valheim_plus.cfg
   "
```

**Comment by spannerman79** [comment]
> You can just use type set to BepInExFull 0.o

Well seeing as you released/pushed these changes I thought I would actually use `BepInExFull` but alas doesn't work.


```docker-compose.yml
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    ports:
      - 2456:2456/udp
      - 2457:2457/udp
      - 2458:2458/udp
    environment:
      - PORT=2456
      - NAME="removed"
      - WORLD="removed"
      - PASSWORD="removed"
      - TZ=Australia/Sydney
      - PUBLIC=0
      - AUTO_UPDATE=0
      - AUTO_UPDATE_SCHEDULE="0 1 * * *"
      - AUTO_BACKUP=1
      - AUTO_BACKUP_SCHEDULE="*/15 * * * *"
      - AUTO_BACKUP_REMOVE_OLD=1
      - AUTO_BACKUP_DAYS_TO_LIVE=3
      - AUTO_BACKUP_ON_UPDATE=1
      - AUTO_BACKUP_ON_SHUTDOWN=1
      - DEBUG_MODE=1 # added for testing
      - TYPE=BepInExFull
      - "MODS=
        https://github.com/valheimPlus/ValheimPlus/releases/download/0.9.5.5/ValheimPlus.dll,
        https://github.com/valheimPlus/ValheimPlus/releases/download/0.9.5.5/valheim_plus.cfg
        "
    volumes:
      - /share/Valheim_Docker/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - /share/Valheim_Docker/server:/home/steam/valheim
      - /share/Valheim_Docker/backups:/home/steam/backups
```

That was done with a `docker-compose up` and it did **not** grab and push in BepInExFull.

From the logs;

```
[ODIN][INFO]  - Executing: /home/steam/valheim/valheim_server.x86_64 .....
[ODIN][INFO]  - --------------------------------------------------------------------------------------------------------------
[ODIN][DEBUG] - Env var default 'ODIN_WORKING_DIR': '/home/steam/valheim'
[ODIN][DEBUG] - Env var default 'LD_LIBRARY_PATH': '/home/steam/valheim/linux64'
[ODIN][DEBUG] - Setting up base command
[ODIN][DEBUG] - Env var default 'APPID': '892970'
[ODIN][DEBUG] - Env var default 'ODIN_WORKING_DIR': '/home/steam/valheim'
[ODIN][INFO]  - Executable: /home/steam/valheim/valheim_server.x86_64
[ODIN][INFO]  - Launching Command...
[ODIN][DEBUG] - Env var default 'LD_PRELOAD': ''
[ODIN][DEBUG] - Env var default 'DOORSTOP_LIB': 'libdoorstop_x64.so'
[ODIN][DEBUG] - Env var default 'ODIN_WORKING_DIR': '/home/steam/valheim'
[ODIN][DEBUG] - Env var default 'DOORSTOP_LIBS': '/home/steam/valheim/doorstop_libs'
[ODIN][DEBUG] - Env var default 'LD_LIBRARY_PATH': './linux64:/home/steam/valheim/doorstop_libs'
[ODIN][DEBUG] - Env var default 'ODIN_WORKING_DIR': '/home/steam/valheim'
[ODIN][DEBUG] - Env var default 'DOORSTOP_INVOKE_DLL_PATH': '/home/steam/valheim/BepInEx/core/BepInEx.Preloader.dll'
[ODIN][DEBUG] - Env var default 'ODIN_WORKING_DIR': '/home/steam/valheim'
[ODIN][DEBUG] - Env var default 'DOORSTOP_CORLIB_OVERRIDE_PATH': '/home/steam/valheim/unstripped_corlib'
[ODIN][DEBUG] - Env var default 'ODIN_WORKING_DIR': '/home/steam/valheim'
[ODIN][DEBUG] - Env var default 'DOORSTOP_LIBS': '/home/steam/valheim/doorstop_libs'
[ODIN][DEBUG] - Env var default 'DYLD_LIBRARY_PATH': '/home/steam/valheim/doorstop_libs'
[ODIN][DEBUG] - Env var default 'ODIN_WORKING_DIR': '/home/steam/valheim'
[ODIN][DEBUG] - Env var default 'DOORSTOP_LIBS': '/home/steam/valheim/doorstop_libs'
[ODIN][DEBUG] - Env var default 'DOORSTOP_LIB': 'libdoorstop_x64.so'
[ODIN][DEBUG] - Env var default 'DYLD_INSERT_LIBRARIES': '/home/steam/valheim/doorstop_libs/libdoorstop_x64.so'
[ODIN][DEBUG] - Env var default 'DYLD_INSERT_LIBRARIES': '/home/steam/valheim/doorstop_libs/libdoorstop_x64.so'
[ODIN][INFO]  - Checking for BepInEx Environment...
[ODIN][DEBUG] - LD_PRELOAD: libdoorstop_x64.so
[ODIN][DEBUG] - LD_LIBRARY_PATH: ./linux64:/home/steam/valheim/doorstop_libs
[ODIN][DEBUG] - DOORSTOP_ENABLE: TRUE
[ODIN][DEBUG] - DOORSTOP_INVOKE_DLL_PATH: /home/steam/valheim/BepInEx/core/BepInEx.Preloader.dll
[ODIN][DEBUG] - DOORSTOP_CORLIB_OVERRIDE_PATH: /home/steam/valheim/unstripped_corlib
[ODIN][DEBUG] - DYLD_LIBRARY_PATH: /home/steam/valheim/doorstop_libs
[ODIN][DEBUG] - DYLD_INSERT_LIBRARIES: /home/steam/valheim/doorstop_libs/libdoorstop_x64.so
[ODIN][DEBUG] - Checking for BepInEx specific files...
[ODIN][DEBUG] - Path /home/steam/valheim/unstripped_corlib does not exist
[ODIN][DEBUG] - Uhh ohh!!! Looks like you are missing something.
[ODIN][INFO]  - Everything looks good! Running normally!
[ODIN][INFO]  - Success, daemonized
[ODIN][DEBUG] - Env var default 'WEBHOOK_URL': ''
[ODIN][DEBUG] - Skipping notification, no webhook supplied!
```

The tree of `/share/Valheim_Docker/server`

```
.
├── config.json
├── linux64
│   └── steamclient.so
├── LinuxPlayer_s.debug
├── logs
│   ├── auto-backup.out
│   ├── auto-update.out
│   ├── valheim_server.err
│   └── valheim_server.log
├── output.txt
├── server_exit.drp
├── start_server.sh
├── start_server_xterm.sh
├── steam_appid.txt
├── steamapps
│   ├── appmanifest_896660.acf
│   ├── downloading
│   ├── libraryfolders.vdf
│   ├── shadercache
│   └── temp
├── steamclient.so
├── UnityPlayer_s.debug
├── UnityPlayer.so
├── Valheim Dedicated Server Manual.pdf
├── valheim_server_Data
│   ├── app.info
│   ├── boot.config
│   ├── globalgamemanagers
│   ├── globalgamemanagers.assets
│   ├── globalgamemanagers.assets.resS
│   ├── level0
│   ├── level0.resS
│   ├── level1
│   ├── level2
│   ├── level3
│   ├── level4
│   ├── level4.resS
│   ├── Managed
│   │   ├── assembly_googleanalytics.dll
│   │   ├── assembly_guiutils.dll
│   │   ├── assembly_lux.dll
│   │   ├── assembly_postprocessing.dll
│   │   ├── assembly_simplemeshcombine.dll
│   │   ├── assembly_steamworks.dll
│   │   ├── assembly_sunshafts.dll
│   │   ├── assembly_utils.dll
│   │   ├── assembly_valheim.dll
│   │   ├── EditorToUnityLinkerData.json
│   │   ├── Mono.Security.dll
│   │   ├── mscorlib.dll
│   │   ├── response.rsp
│   │   ├── System.Configuration.dll
│   │   ├── System.Core.dll
│   │   ├── System.dll
│   │   ├── System.Xml.dll
│   │   ├── TypesInScenes.xml
│   │   ├── UnityEngine.AIModule.dll
│   │   ├── UnityEngine.AndroidJNIModule.dll
│   │   ├── UnityEngine.AnimationModule.dll
│   │   ├── UnityEngine.AssetBundleModule.dll
│   │   ├── UnityEngine.AudioModule.dll
│   │   ├── UnityEngine.ClothModule.dll
│   │   ├── UnityEngine.CoreModule.dll
│   │   ├── UnityEngine.DirectorModule.dll
│   │   ├── UnityEngine.dll
│   │   ├── UnityEngine.GridModule.dll
│   │   ├── UnityEngine.IMGUIModule.dll
│   │   ├── UnityEngine.InputLegacyModule.dll
│   │   ├── UnityEngine.InputModule.dll
│   │   ├── UnityEngine.ParticleSystemModule.dll
│   │   ├── UnityEngine.Physics2DModule.dll
│   │   ├── UnityEngine.PhysicsModule.dll
│   │   ├── UnityEngine.ScreenCaptureModule.dll
│   │   ├── UnityEngine.SharedInternalsModule.dll
│   │   ├── UnityEngine.SubsystemsModule.dll
│   │   ├── UnityEngine.TerrainModule.dll
│   │   ├── UnityEngine.TextRenderingModule.dll
│   │   ├── UnityEngine.TilemapModule.dll
│   │   ├── UnityEngine.UI.dll
│   │   ├── UnityEngine.UIElementsModule.dll
│   │   ├── UnityEngine.UIModule.dll
│   │   ├── UnityEngine.UnityAnalyticsModule.dll
│   │   ├── UnityEngine.UnityWebRequestModule.dll
│   │   ├── UnityEngine.UnityWebRequestWWWModule.dll
│   │   ├── UnityEngine.VFXModule.dll
│   │   ├── UnityEngine.VideoModule.dll
│   │   ├── UnityEngine.VRModule.dll
│   │   ├── UnityEngine.XRModule.dll
│   │   └── UnityLinkerToEditorData.json
│   ├── MonoBleedingEdge
│   │   ├── etc
│   │   │   └── mono
│   │   │       ├── 2.0
│   │   │       │   ├── Browsers
│   │   │       │   │   └── Compat.browser
│   │   │       │   ├── DefaultWsdlHelpGenerator.aspx
│   │   │       │   ├── machine.config
│   │   │       │   ├── settings.map
│   │   │       │   └── web.config
│   │   │       ├── 4.0
│   │   │       │   ├── Browsers
│   │   │       │   │   └── Compat.browser
│   │   │       │   ├── DefaultWsdlHelpGenerator.aspx
│   │   │       │   ├── machine.config
│   │   │       │   ├── settings.map
│   │   │       │   └── web.config
│   │   │       ├── 4.5
│   │   │       │   ├── Browsers
│   │   │       │   │   └── Compat.browser
│   │   │       │   ├── DefaultWsdlHelpGenerator.aspx
│   │   │       │   ├── machine.config
│   │   │       │   ├── settings.map
│   │   │       │   └── web.config
│   │   │       ├── browscap.ini
│   │   │       ├── config
│   │   │       ├── mconfig
│   │   │       │   └── config.xml
│   │   │       └── registry
│   │   │           └── last-btime
│   │   └── x86_64
│   │       ├── libmonobdwgc-2.0.so
│   │       └── libMonoPosixHelper.so
│   ├── Plugins
│   │   ├── libsteam_api.so
│   │   └── Steamworks.NET.txt
│   ├── Resources
│   │   ├── unity_builtin_extra
│   │   ├── unity default resources
│   │   └── UnityPlayer.png
│   ├── resources.assets
│   ├── resources.assets.resS
│   ├── sharedassets0.assets
│   ├── sharedassets0.assets.resS
│   ├── sharedassets1.assets
│   ├── sharedassets1.assets.resS
│   ├── sharedassets1.resource
│   ├── sharedassets2.assets
│   ├── sharedassets3.assets
│   ├── sharedassets3.assets.resS
│   ├── sharedassets3.resource
│   └── sharedassets4.assets
└── valheim_server.x86_64

22 directories, 121 files

```

**Comment by mbround18** [comment]
> Edited:
> Please ignore, looks like DockerHub was being dumb and whatever CDN they use didn't update for my country until **literal** 10 mins after I posted this.
> 
> I did check dockerhub to see when the image was there but yeah.. their CDN....

Lol, got it working now? :P

**Comment by ouvoun** [comment]
@mbround18  Awesome, great to see this merged.

At some point I think there was a regression, though. Tested using `TYPE=ValheimPlus`, and every time the server restarts the valheim_plus.cfg config within BepInEx/config gets reset to the default. Maybe that's intended, but I'd assume that it is not. :)

**Comment by LovecraftianHorror** [comment]
@ouvoun Thanks for the heads up!

The server will overwrite all files from mods when it updates which can happen on startup depending on your configuration. This is undesirable behavior for config files though. Thinking on it more do you think doing something like writing potential config files with a `.new` appended instead of overwriting them would be appropriate, that way you have easy access to the most recent config file shipped with the mod if you need to make changes to that and start using it?

So essentially instead of overwriting `valheim_plus.cfg` it would copy it over as a new `valheim_plus.cfg.new` next to the existing config file that you could make changes to and start using if required.

In an ideal world it could _automagically_ merge the old config file with any changes in the new one, but that's unlikely to happen since it would require specific knowledge of the config files and what changes are valid.

**Comment by ouvoun** [comment]
Hey @LovecraftianHorror! Thanks for the reply.

I like the idea of appending a suffix to the new versions of the config files without actually overwriting them. I think doing a merge would be nearly impossible to generalize to mods outside of V+, so the strategy of keeping both configs seems the most reasonable.

Would you imagine this would be an explicit behavior specifically for the `BepInEx/config` directory?

**Comment by LovecraftianHorror** [comment]
I was planning on just applying this behavior to all files that fit a set of file extensions likely to be configs since I assumed many mods could have config files in different locations, but maybe that's not the case.

I'll have to sample a large set of mods to see if I can glean any extra information. I like the ability to backup mod configs, but want to see if there are any potentially better or more flexible techniques that we could try

All in all thanks for the input, it helped give me quite a few new ideas!

**Comment by ouvoun** [comment]
Sounds legit! Thanks for your work on this.
