### ISSUE TITLE
Container startup fails:  exec user process caused: exec format error

### ISSUE THREAD

**Issue by lankester5** [mbround18/valheim-docker#291]
Hi,

I am trying to get this server to run on a Pi4 4Gb model with the latest version rasbain installed.

I have docker installed, however when running docker-compose i get the following error
Starting valheim_valheim_1 ... done
Attaching to valheim_valheim_1
valheim_1  | standard_init_linux.go:219: exec user process caused: exec format error
valheim_valheim_1 exited with code 1

I am not 100% sure of how docker for the Pis hardware architecture differs from it running on x86.
It may well be that I am trying to ask too much from the Pi.

It would be nice to be able to run this on the pi though.

Thanks,
Aron

**Comment by lankester5** [comment]
This is while running the standard example docker-compose file in the guide

**Comment by lankester5** [comment]
So the container is based on valheim-odin, I wonder if building valheim-odin on an arm64 based OS would be possible and would enable making a Raspberry Pi compatible container.
perhaps Ubuntu Server for Pi - https://ubuntu.com/download/raspberry-pi

**Comment by LovecraftianHorror** [comment]
I am pretty sure that running it on the Pi (or other ARM computers) would require emulation or other similar translation layer. Steam only supports x86_64 AFAIK, so `steamcmd` (used by this container) and valheim's dedicated server provided by `steamcmd` both don't support ARM.

This is really outside our realm of control. There are guides for getting x86_64 working on Pis in various ways, but I can't imagine the server could handle much after the performance hit.

**Comment by lankester5** [comment]
That's fair enough, I was digging through and found that the valheim Server its self is an x86_64 application, you are right.
given that the Pi4 is at the low end of recommended specs for the server I dont think there is any headroom for instruction set translation.
Thanks for your reply

**Comment by lankester5** [comment]
In principle it would be amazing to be able to have a quad core, 4Gb ram micro PC that only costs £35 able to run gaming servers.

**Comment by LovecraftianHorror** [comment]
I definitely understand your desire for being able to run more game servers on a Pi. Hopefully Valve ends up supporting more architectures in the future so that this is no longer an issue (ARM seems to be getting more and more popular).

I did find [this reddit thread](https://www.reddit.com/r/valheim/comments/llvkgr/how_to_run_valheim_dedicated_server_on_raspberry/) talking about getting valheim running on a Pi with some interesting setup if you're interested in trying out that.

**Comment by lankester5** [comment]
Thanks :) I will take a look
