### ISSUE TITLE
[BUG] Configs are getting overwritten by Odin

### ISSUE THREAD

**Issue by mbround18** [mbround18/valheim-docker#294]
## Discussion Post

To run a passwordless server a couple of things need to be done;

1. Make sure that you are using ValheimPlus (or modded in some way to bypass that "feaure")
2. `disableServerPassword=true` in `BepInEx/config/valheim_plus.cfg` (Using V+ for example)
3. The server **cannot** be public ( `-public 0`)

I have tested this out by creating a stock standard Valheim server (steamcmd etc), grabbing ValheimPlus directly from their github, extracting it, editing V+ config (only changed `disableServerPassword=true`), and ran it ( `./start_server_bepinex.sh -name "MyValheimPlusServer" -port 2456 -world "myworld" -public 0`

I was able to connect in without a password (Direct IP, using localhost/127.0.0.1) and didn't need to enter a password.

The issue is I cannot do this with the way Odin or whatever script checks are in place.  Even with the correct requirements done - Odin prevents the start of the server, or in facts push's a password start flag which no matter what the setting in V+ you will still need that _oh so hard to guess_ password :stuck_out_tongue: 

Suggestions:

I was thinking since the more recent mod update was pushed the **only** way to ensure that no password was defined and allowed Odin to contine would be to ensure that it was anything but `TYPE=Vanilla` and a **must**, `PUBLIC=0`. In fact even having `PUBLIC=1` even with the config value set in V+ the server will fail as if you do not have a password.

Edit:  Using latest docker image at creation of this issue;

```
docker pull mbround18/valheim
Using default tag: latest
latest: Pulling from mbround18/valheim
Digest: sha256:06eb40108fb9aef3bb3465c1b667e6897988ed04fca8aa1c76e396fa4e8a9313
Status: Image is up to date for mbround18/valheim:latest
docker.io/mbround18/valheim:latest
```

_Originally posted by @spannerman79 in https://github.com/mbround18/valheim-docker/discussions/293_

## Bug/Work breakdown

Mod configurations are getting overridden by Odin extracting files to the mod locations. From conversations, the approach we would like to implement would be checking for whether the file is a configuration file and if so, write to the config file name but with the suffix of `.new`

## Acceptance Critera

- Iterate over files and make an exception for configuration files. 
- Overwrite dll files without any exception.

**Comment by LovecraftianHorror** [comment]
I should have a PR out for this later tonight. @spannerman79 since you seem pretty familiar with all this do you know the common file extensions for configs used in mods? I was planning on downloading a large set and checking to get a sample, but it'd be good to have your input too

**Comment by spannerman79** [comment]
Depending on the mods (yeah, I _know_, no set standard, its minecraft, bukkit and MCP all over again) they are usually all under `/path/to/BepInEx/config`.

If you have map sharing enabled in V+ there is one other location, its `/path/to/BepInEx/vplus-data`.  If you are going to plan for a backup that is one location that would be handy to have backed up.

As to the actual config extensions - 

```
├── aedenthorn.CraftFromContainers.cfg
├── aedenthorn.InstantMonsterDrop.cfg
├── aedenthorn.NexusUpdate.cfg
├── Aluviel.VOnline.cfg
├── BepInEx.cfg
├── com.bkeyes93.PlantingPlus.cfg
├── com.lvh-it.valheim.useequipmentinwater.cfg
├── gg.khairex.usefultrophies.cfg
├── HookGenPatcher.cfg
├── Menthus.bepinex.plugins.BetterTrader.cfg
├── org.itskaa.vchat.cfg
├── org.jrobsonchase.valheim.plugins.positionalaudio.cfg
├── randyknapp.mods.epicloot.cfg
├── randyknapp.mods.extendeditemdataframework.cfg
├── swaz.surtlingboat.cfg
└── valheim_plus.cfg

0 directories, 16 files
```

Thats on my docker container at the moment.  Most other mods I've seen are usually client sided.  I think I even have a couple of mods on there that might not even have to be on there (ie positionalaudio ).

**Comment by spannerman79** [comment]
Suggestion: something to look at too https://github.com/dyoung522/valheim-plus-installer

**Comment by mbround18** [comment]
We have a fix for this already, we are going to do some paired programming on the issue later today and should have something ready to go out today/tomorrow.

**Comment by spannerman79** [comment]
The linked merge does not apply to this issue.

_Again_, please re-read what I _actually_ stated https://github.com/mbround18/valheim-docker/issues/292

> To run a passwordless server a couple of things need to be done;
> 
> Make sure that you are using ValheimPlus (or modded in some way to bypass that "feaure")
> disableServerPassword=true in BepInEx/config/valheim_plus.cfg (Using V+ for example)
> The server cannot be public ( -public 0)
> I have tested this out by creating a stock standard Valheim server (steamcmd etc), grabbing ValheimPlus directly from their github, extracting it, editing V+ config (only changed disableServerPassword=true), and ran it ( ./start_server_bepinex.sh -name "MyValheimPlusServer" -port 2456 -world "myworld" -public 0
> 
> I was able to connect in without a password (Direct IP, using localhost/127.0.0.1) and didn't need to enter a password.
> 
> The issue is I cannot do this with the way Odin or whatever script checks are in place. Even with the correct requirements done - Odin prevents the start of the server, or in facts push's a password start flag which no matter what the setting in V+ you will still need that oh so hard to guess password

**Comment by mbround18** [comment]
So, @spannerman79 this requires password to become optional rather than required?

**Comment by spannerman79** [comment]
Yes, with conditions that I outlined in my original closed issue.

What prevents this is whatever logic check is in place - either by Odin/script/whatever.

**Comment by mbround18** [comment]
@spannerman79 I am back from being out of town, ill take a look at this after work <3

**Comment by spannerman79** [comment]
No probs, when it comes to open sourced software (in this case BSD 3-Clause License
software) I _never_ expect immediate to-the-second resolutions.

**Comment by mbround18** [comment]
![image](https://user-images.githubusercontent.com/12646562/112871249-edc9db80-9073-11eb-904a-e9c7ade1bd67.png)

Was able to jam a lil out on break, should have something up by lunch :)

**Comment by mbround18** [comment]
![image](https://user-images.githubusercontent.com/12646562/112873736-e5bf6b00-9076-11eb-919b-da991035b83c.png)

@spannerman79 that is all this needs right? The ability to not set the password?

**Comment by spannerman79** [comment]
For the sake of logic checking (and less issues being raised) `TYPE` **cannot** be `Vanilla` and `PUBLIC` **has** to be `0`

If `PUBLIC=1` V+ will fail unless you have set a password

**Comment by mbround18** [comment]
@spannerman79, if youd like to give it a whirl its on `mbround18/valheim:294-no-password-fix`

[See here for docker hub info](https://hub.docker.com/layers/mbround18/valheim/294-no-password-fix/images/sha256-19ca765f4c7b7457c2ec1f70f6b9383d6659155a2fbba2b19a693ce3bd207187?context=repo)

**Comment by mbround18** [comment]
@spannerman79 hows this looking https://github.com/mbround18/valheim-docker/pull/319?

**Comment by spannerman79** [comment]
Hi sorry been super busy with other things.

Just spun up a test docker container, added in V+ with the needed config change, set the server not to be public and I was able to connect in without a password.

Great work.

No, not an april fools joke either - _just in case_.  Actually works correctly now.

**Comment by LovecraftianHorror** [comment]
Ah sorry, I missed that the password flag can't be passed in your original issue.

Just got through looking over the changes and all of it looks good to me :+1:. The only part I was worried about was not properly warning/erroring when not passing a password when one was needed, but it looks like that is all covered!

Thanks for your patience @spannerman79 !
