### ISSUE TITLE
Configure dataPerSec?

### ISSUE THREAD

**Issue by jonneymendoza** [mbround18/valheim-docker#300]
Hi, is it possible to set a env variable where it edits and sets the dataPerSec as per this article below:

https://indiefaq.com/guides/valheim-fix-for-multiplayer-lag.html

Basically, without this modification,  Valheim lags a lot as it only sends 30kbps max to all clients connected

**Comment by mbround18** [comment]
This seems like a discussion question.

**Comment by mbround18** [comment]
As for this article no, it's t would require editing a dll and recompiling it. Which would be to chunky to include all the mono repos

**Comment by mbround18** [comment]
You can accomplish this with Longship mod or Valheim Plus

**Comment by spannerman79** [comment]
Indeed.  This should be done with Longship, Valheim Plus and there are a couple of other mods that do this too.

In regards to V+ - https://github.com/valheimPlus/ValheimPlus/blob/0.9.5.5/valheim_plus.cfg#L436..L437
