### ISSUE TITLE
[BUG]: Auto-backup script ignores AUTO_BACKUP_PAUSE_WITH_NO_PLAYERS environment variable

### ISSUE THREAD

**Issue by anonymus19941** [mbround18/valheim-docker#314]
The newly added *AUTO_BACKUP_PAUSE_WITH_NO_PLAYERS* flag is currently "ignored" in [auto-backup.sh](https://github.com/mbround18/valheim-docker/blob/main/src/scripts/auto_backup.sh) because the PUBLIC variable is not set in the cron file and is therefore always unset in the script.

Most environment variables get copied to the cron file by [entrypoint.sh](https://github.com/mbround18/valheim-docker/blob/main/src/scripts/entrypoint.sh), l. 55-75, but not PUBLIC. When *auto-backup.sh* is then called by cron, PUBLIC is not set and defaults to 0. Thus, the first part of the condition in line 10 is always true.

### Fix:
Add `PUBLIC=${PUBLIC}` to the environment construction part in *entrypoint.sh* (`setup_cron`).

**Comment by mbround18** [comment]
Rip, good callout :P thank you, ill toss up a PR later.
