### ISSUE TITLE
Use SIGINT for server shutdown 

### ISSUE THREAD

**Issue by spion06** [mbround18/valheim-docker#32]
as of version 0.143.5 the server process no longer uses the file marker to note shutdown. It instead will use honor SIGINT. 

https://steamcommunity.com/games/892970/announcements/detail/3059603085893784927

Since this is no longer used https://github.com/mbround18/valheim-docker/blob/main/src/files/server_exit.rs#L14-L18 should be updated to send a SIGINT to the process rather than writing to the file and waiting for shutdown

**Comment by Shuro** [comment]
I tried to come with a way to send SIGINT to the docker container, noticing that it also saves the wrong PID in the pidfile:

``` root@099cacafa16c:/home/steam/valheim# ps auxf
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root       148  0.0  0.0   3992  3344 pts/0    Ss   16:22   0:00 /bin/bash
root       466  0.0  0.0   7640  2772 pts/0    R+   16:29   0:00  \_ ps auxf
root         1  0.0  0.0   3736  2912 ?        Ss   16:09   0:00 /bin/bash /init.sh
root        37  0.0  0.0   6164  2628 ?        S    16:09   0:00 su -ps /bin/bash --login steam -c /bin/bash /home/s
steam       38  0.0  0.0   3652  2720 ?        Ss   16:09   0:00  \_ /bin/bash /home/steam/scripts/entrypoint.sh
steam       97  0.0  0.0   2328   752 ?        S    16:09   0:00      \_ tail -f /home/steam/valheim/output.log
steam       94  163  1.2 8477648 1713216 ?     Rl   16:09  31:27 /home/steam/valheim/valheim_server.x86_64 -port 245
steam       95  0.0  0.0   2300   684 ?        S    16:09   0:00 tee ./output.log
root@099cacafa16c:/home/steam/valheim# cat valheim_server.pid
95
root@099cacafa16c:/home/steam/valheim#
```

**Comment by mbround18** [comment]
Good call out, ill take a look at putting in a fix for this today

**Comment by mbround18** [comment]
Fix for this is live on `:latest` and working on my production servers. Would someone mind giving it a whirl to confirm?

![image](https://user-images.githubusercontent.com/12646562/107556228-61338e80-6b95-11eb-8086-3ee61144ec79.png)

**Comment by Shuro** [comment]
not familiar with rust, but the output of pidof should be without any new lines, so the replace would be unneccesary. It could be problematic if there are multiple processes tho. 

Example:
![grafik](https://user-images.githubusercontent.com/944030/107559797-d24a6480-6bdc-11eb-8d69-ad93fa3bdc09.png)

**Comment by Shuro** [comment]
Tested it with my production server and it didn't seem to work out. 

Left: Stopped container, pulled newest image, started, waited and stopped.
Right: `docker-compose logs -f` output after start.
![grafik](https://user-images.githubusercontent.com/944030/107560669-ecd10d80-6bdd-11eb-972b-be3c3cb0cebb.png)

**Comment by mbround18** [comment]
For the pid, I don't support running multiple servers in one container and currently it returns the pid if the main process.



I'll check outputs in a little bit

**Comment by mbround18** [comment]
@Shuro tossed up #38 which handles if you decide to run multiple processes. It finds it by name and sends SIGINT via rust rather than using the operating system commands.

**Comment by spion06** [comment]
looks to work for me! I do have some issues with the entrypoint.sh actually triggering the exit trap on kubernetes. I think if you were to change https://github.com/mbround18/valheim-docker/blob/main/src/scripts/init.sh#L74 to do an exec it would behave as expected.

**Comment by mbround18** [comment]
Great minds think alike :P I am actually writing that bit right now

**Comment by Shuro** [comment]
Got the following now: 
```shuro@mainframe ~/games $ docker-compose pull
Pulling valheim ... done
(reverse-i-search)`u': docker-compose p^Cl
shuro@mainframe ~/games $ docker-compose up -d
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Creating games_valheim_1 ... error

ERROR: for games_valheim_1  Cannot start service valheim: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/init.sh": permission denied: unknown

ERROR: for valheim  Cannot start service valheim: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/init.sh": permission denied: unknown
ERROR: Encountered errors while bringing up the project.
```

**Comment by mbround18** [comment]
Hey @spion06 when I added the trap to the init it doesnt seem to shutdown the server correctly it still exits with 137

**Comment by spion06** [comment]
yeah that's most likely due to su swallowing it. gosu might be a better option here https://github.com/tianon/gosu

**Comment by mbround18** [comment]
Hmm I added gosu and the exit coming out is still 137... I will have to do some more digging on this

**Comment by Shuro** [comment]
Yes, looks fine now. Exiting with cod 143, which means all is fine (SIGTERM was sent to docker container).

@mbround18 Only suggestion from my side. Stop via odin first and then kill the `tee`? 😅 
This way you could confirm the log entries for saving the world, etc, which are lost if you kill `tee` first.
