### ISSUE TITLE
Tell Odin to add -console

### ISSUE THREAD

**Issue by shauder** [mbround18/valheim-docker#333]
I may be missing it but I cannot find out how to tell odin to start the server with -console to enable the console. Which is needed for the latest update.

**Comment by mbround18** [comment]
is it needed? I vaguely remember that `-console` was only for desktop client

**Comment by shauder** [comment]
One reason could be enabling cheats or server administration through the game. But the main reason I wanted to add it is the new update to terrain mechanics and the need to use "optterrain" console command to convert already modified terrain to the new mechanics/system. I will try your suggestion and report back as soon as I can try.

From the patch notes:
For existing areas where heavy terrain modifications have been made before this patch we have added a special console command “optterrain” that basically converts all the old terrain modifications in the nearby area to the new system. To use the “optterrain” console command, you first need to enable the ingame console by adding “-console” as a launch argument for the game

**Comment by mbround18** [comment]
Are you sure this needs to be enabled on the server? or could you enable it on your client? In Valheim, your client drives what you have access to. For example, I am a server admin on ~15 servers with my steam 64 id on the admin list. We use the following mod to use admin command, https://www.nexusmods.com/valheim/mods/8

**Comment by shauder** [comment]
Ah I see and I think I understood it wrong. Thanks for the quick responses.
