### ISSUE TITLE
Configuring the auto update time

### ISSUE THREAD

**Issue by FrederikP** [mbround18/valheim-docker#37]
The docs say:
```
Set to 1 if you want your container to auto update! This means at 1 am it will update, stop, and then restart your server.
```

Is there a way to configure that so it restarts at 9am for example?

**Comment by mbround18** [comment]
Not atm no, this is something I can add

**Comment by FrederikP** [comment]
Would be really cool. It's a nice to have.

As a workaround, would it currenly be possible to set TZ to a certain timezone so that I can decide when the upgrade will run?
E.g.: I'm in Germany (UTC +1) and I want it to run in the morning/noon. So when I choose a timezone that is US westcoast or so, then it should run ~9 hours later than it would, when I would choose the "correct" timezone for Germany? Would that work?

Thank you, again :)

**Comment by mbround18** [comment]
Yeah! Technically as a work around all you have to do set the time zone to match when you want it to run or as close as possible. For example, mine uses an african time zone because I want it to restart at 3pm for me on the west coast. Ill have to out this in as a feature in a couple of days. (Out of town atm)

**Comment by mbround18** [comment]
Added a way to specify the schedule for the cronjob #53

**Comment by mbround18** [comment]
Use variable 
`AUTO_UPDATE_SCHEDULE`

Example: 
```sh
AUTO_UPDATE_SCHEDULE="0 1 * * *"
```

Useful site for figuring out cron timings

https://crontab.guru/#0_1_*_*_*

**Comment by mbround18** [comment]
[valheim-server.log](https://github.com/mbround18/valheim-docker/files/5974023/valheim-server.log)
