### ISSUE TITLE
Huginn /metrics endpoint lacks trailing \n

### ISSUE THREAD

**Issue by roobre** [mbround18/valheim-docker#399]
Currently, the `/metrics` endpoint does not end each metric line with a newline character:

```
[root@Terabox integrations.d]# curl localhost:2480/metrics
valheim_online{name="Deliverance", version="0.155.7", map="Deliverance"} 1
valheim_current_player_count{name="Deliverance", version="0.155.7", map="Deliverance"} 0
valheim_max_player_count{name="Deliverance", version="0.155.7", map="Deliverance"} 64
valheim_bepinex_installed{name="Deliverance", version="0.155.7", map="Deliverance"} 0[root@Terabox integrations.d]#
```

This confuses prometheus parsers:

`error="text format parsing error in line 4: unexpected end of input stream"`

This seems like a really easy fix but sadly I have zero knowledge of Rust so I cannot write a quick patch for it :(

**Comment by mbround18** [comment]
huh didnt know it needed a trailing slash 0.o

**Comment by mbround18** [comment]
how does prometheus ingest the output of the curl command? 0.o

**Comment by roobre** [comment]
> huh didnt know it needed a trailing slash 0.o

It is documented here, from what I can see: https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md#text-format-details

> how does prometheus ingest the output of the curl command? 0.o

It doesn't, I just pasted it here for reference so the lack of newline could be seen.

**Comment by mbround18** [comment]
@roobre deploy is running right now, will ping again when its released. Would you mind validating?

**Comment by mbround18** [comment]
@roobre release is good to go, should have that trailing `\n`
https://github.com/mbround18/valheim-docker/releases/tag/v1.4.1

**Comment by roobre** [comment]
Hi @mbround18, thanks for fixing this so quickly!

I can confirm that this is working now and I can parse the prometheus metrics as expected.
