### ISSUE TITLE
Odin unable to find Valheim process on linux operating systems

### ISSUE THREAD

**Issue by Finomnis** [mbround18/valheim-docker#442]
Linux operating systems do not support process names with more than 15 characters:

 - https://stackoverflow.com/questions/23534263/what-is-the-maximum-allowed-limit-on-the-length-of-a-process-name
 - https://docs.rs/sysinfo/0.20.3/sysinfo/trait.ProcessExt.html#tymethod.name

This causes odin to not find the running valheim process and to incorrectly assume that it is not running.
`get_process_by_name("valheim_server.x86_64")` returns an empty array, and if you list process names and print them, the valheim server will be listed as `"valheim_server."`.

Solution: search only for the first 15 characters of the valheim server process name.

Proposed fix: https://github.com/mbround18/valheim-docker/pull/441

**Comment by mbround18** [comment]
Fixed with #441
