### ISSUE TITLE
Client updated, now can't connect

### ISSUE THREAD

**Issue by Zeneixe** [mbround18/valheim-docker#462]
The server I set up is set on AUTO_UPDATE=1 but it doesn't seems to be auto updating hence I can't connect to it due to "incompatible version".

Any ways to force an update?

**Comment by Zeneixe** [comment]
It was enough to restart the server.

**Comment by mbround18** [comment]
@Zeneixe please ensure you are running image version v1.4.9 :) there was a bug fix for shutdown in v1.4.7+
