### ISSUE TITLE
Stuck at starting to load scene

### ISSUE THREAD

**Issue by CodeInKlingon** [mbround18/valheim-docker#49]
After running the docker compose command the setup stops just after the following line:
<img width="1324" alt="Screen Shot 2021-02-11 at 2 34 24 PM" src="https://user-images.githubusercontent.com/9805593/107689066-5d2b6d80-6c76-11eb-968a-01ff6532e056.png">
Any thoughts as to why this is happening?

**Comment by Richi2293** [comment]
Same problem I had, I solved it by increasing the ram to 2Gb and the cpu to two cores

**Comment by krovikan666** [comment]
@Richi2293 I am running into a similar issue, where did you change the RAM and CPU core usage configuration?

**Comment by Richi2293** [comment]
I am using Digitalocean as hosting, I resized the server and it worked. 
Except that at the moment I can't see the server but at least it didn't crash at that point in the screenshot

**Comment by mbround18** [comment]
@Richi2293 You can use the server browser in steam to direct connect

https://imgur.com/gallery/aXFpcKg

**Comment by Shuro** [comment]
Sometimes you need to use the :2457 port. Also yea make sure you have at least 2-3 GB of memory free. The Game might not be heavy on the graphics, but it uses some memory for the big world.

**Comment by Richi2293** [comment]
Okok thanks.

(Question out of section)
Which hosting do you use? 
I had a Digitalocean but it seems too expensive for such a server

**Comment by Shuro** [comment]
Personally I use a private physical server, but that is way more expensive for only a game server. :) Maybe you should try hosted gameserver alternatives like https://www.g-portal.com

**Comment by CodeInKlingon** [comment]
Upgrading my vps solved this issue. For anyone curious I tried with digital oceans 1 vCPUs 1GB / 25GB Disk droplet and that wouldn't cut it. I also tried OVH     Processor: 1 vCore    RAM: 2 GiB VPS and that also did not cut it.
OVH's Processor: 2 vCore RAM: 4 GiB vps did work and I haven't had any issues yet.
