### ISSUE TITLE
Server stuck at DungeonDB Start 477

### ISSUE THREAD

**Issue by krovikan666** [mbround18/valheim-docker#52]
Env: OpenSuse 15.2
CPU: AMD FX-8320E Eight-Core Processor
RAM: 32Gb

I ran the following docker create:

```
docker create \
  --name valheim \
  -e PUID=1000 -e PGID=1000 \
  -e TZ=America/Edmonton \
  -e NAME="Valheim - GOATS" \
  -e World=Dedicated \
  -e PORT=2456 \
  -e PUBLIC=1 \
  -e PASSWORD=<value> \
  -e AUTO_UPDATE=1 \
  -p 2456:2456/udp \
  -p 2457:2457/udp \
  -p 2458:2458/udp \
  -v /opt/data/ssd2/valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim \
  -v /opt/data/ssd2/valheim/server:/home/steam/valheim \
    --privileged \
   mbround18/valheim:latest
```

However, everything time I tried to create and start the container it gets stucks and never starts up the server. I'm not using docker-compose due to the local environment.

I have attached the logs

[_valheim_logs.txt](https://github.com/mbround18/valheim-docker/files/5969063/_valheim_logs.txt)

**Comment by mbround18** [comment]
based on that log, your server should be running

**Comment by krovikan666** [comment]
Odd because steam isn't able to find it, and telnet even to the docker IP over port 2456 doesn't work.

I checked netstat in the container and it looks like 2457 is open, but not 2456

![image](https://user-images.githubusercontent.com/13492347/107717101-0af74600-6c90-11eb-80e2-fc5e52436b21.png)

**Comment by mbround18** [comment]
inside the docker, whats `pidof valheim_server.x86_64` return?

**Comment by mbround18** [comment]
Minor note, you should not be using a privileged container for this
>     --privileged

**Comment by krovikan666** [comment]
Okay, I don't know what I did, but it's working; maybe it just took a while to register with steam? Not sure, as for privileged, ya I need to properly set up my security profiles but haven't had a chance.

Thank you for your assistance :)
