### ISSUE TITLE
Regarding the docker-compose.yml config

### ISSUE THREAD

**Issue by AtroposOrbis** [mbround18/valheim-docker#55]
Config of getting started guide... (https://github.com/mbround18/valheim-docker/discussions/28)
![image](https://user-images.githubusercontent.com/8618455/107763274-5f380f80-6cfc-11eb-9f21-d063b2679779.png)

and the config used in the README.md... (https://github.com/mbround18/valheim-docker/blob/main/README.md)
![image](https://user-images.githubusercontent.com/8618455/107763349-82fb5580-6cfc-11eb-9d64-51d6eb68294e.png)

Are different from one another. Will this affect anything when spinning up a new container?

**Comment by mbround18** [comment]
Good catch, it shouldn't but I can update it to keep parity

**Comment by mbround18** [comment]
Just merged and matched in docs, thanks for the catch!
