### ISSUE TITLE
Import existing world from Win10/Steam environment

### ISSUE THREAD

**Issue by kieron** [mbround18/valheim-docker#60]
Hi, is it possible to do this, use the container, but take a preexisting world?

Thanks :-)

**Comment by broizter** [comment]
Just put the *.db and *.fwl files into the './valheim/saves/worlds' folder.

**Comment by mbround18** [comment]
you could also just copy the folder to where you want to mount it

Also please, if you have a question use the discussion section so others who have these questions can easily find an answer <3
