### ISSUE TITLE
Not able to see BepInEx overlay in game when using TYPE=BepInEx

### ISSUE THREAD

**Issue by ainglimo-personal** [mbround18/valheim-docker#629]
Hi there! 

I apologize if this question isn't in the scope of what you do because it is mod related, but since we are using TYPE=BepInEx which is a Environment Variable being set in the docker-compose file, I figured I'd check to see if this is an expected issue with the latest Valheim Public test patch. 

Issue: I am not seeing the BepInEx overlay in game after having just installed BepInEx and UpgradeWorld on my client machine, and specifying them in the docker-compose configuration.

I checked the logs and saw that the mods were being installed, and I can now see the UpgradeWorld commands in the dev console, but I don't see the BepInEx overlay on the top left of the screen. I also am getting `Unauthorized to use Upgrade World commands.`

BepInEx version that appears to be installed on the server: 
```
[Message:   BepInEx] BepInEx 5.4.19.0 - valheim_server (11/24/2
022 6:13:56 PM)
```

Is this the updated version that is required in order to support the Mistlands launch to the Public Test version of the game? 

I'm sure I'm missing useful information here, please let me know what more I can provide.

**Comment by spannerman79** [comment]
Out of the scope of this issue tracker

https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/#:~:text=Last%20updated-,5%20months%20ago,-Total%20downloads

In short - beta branches don't have mod support _unless_ stated so by BepInEx devs.

**Comment by ainglimo-personal** [comment]
Ack. Understood. Will close then. Thanks :)
