### ISSUE TITLE
Daily saves clean up

### ISSUE THREAD

**Issue by rdalbuquerque** [mbround18/valheim-docker#664]
Hello!

Is there a way to configure daily saves clean up? it's causing my storage to go full and I honestely don't care about keeping all valheim days. Would be really nice to have an environment variable to configure daily saves cleanup!

**Comment by spannerman79** [comment]
https://github.com/mbround18/valheim-docker#auto-backup

Look/set the en vars from there.

Also - this issue should of been in https://github.com/mbround18/valheim-docker/discussions as per https://github.com/mbround18/valheim-docker/issues/61#issue-807551529

**Comment by mbround18** [comment]
@rdalbuquerque closing issue
