### ISSUE TITLE
Stop messages are not being sent to webhook

### ISSUE THREAD

**Issue by mbround18** [mbround18/valheim-docker#671]
I believe this is still not functional running v2, the started messages still come through, nothing for stopped.

_Originally posted by @jbarnes in https://github.com/mbround18/valheim-docker/discussions/633#discussioncomment-5226432_

**Comment by mbround18** [comment]
@jbarnes how are you stopping your server? if i use ctrl+c on window it doesnt trigger stop notification but if i stop using kubernetes it does. 

![image](https://user-images.githubusercontent.com/12646562/223578441-6fd46830-3a78-4c45-9777-5116bf0d2124.png)

**Comment by jbarnes** [comment]
* Running on ubuntu 20.04 LTS
* I am running `docker compose up`, `docker-compose down` to start/stop gracefully
* Start message comes through no problems, nothing for stop when using the latter
* Additionally even with a full server shutdown (Container is running on an EC2 instance) no change in behaviour
  * I would have anticipated this shutdown behaviour likely would induce a failure to send a stop message, but alas, even the graceful `docker-compose down` is not producing the message.

**Comment by mbround18** [comment]
@jbarnes can you try upping your stop grace period? 
```
stop_grace_period: 3m
```

**Comment by mbround18** [comment]
I can confirm, upping that limit on a server on windows with a xxl world will let it stop

**Comment by jbarnes** [comment]
Can confirm this has resolved the issue.

Thanks @mbround18, may be worth a documentation update to save you from more whingers like me.

Thanks again.
