### ISSUE TITLE
First start have failed

### ISSUE THREAD

**Issue by hdcola** [mbround18/valheim-docker#685]
log is 
```
valheim_1     | [Valheim][steam]: Running Install...
valheim_1     | [ODIN][INFO]  - Installing 896660 to /home/steam/valheim
valheim_1     | [ODIN][INFO]  - steamcmd found in path
valheim_1     | ln: failed to create symbolic link '/home/steam/.steam/root': No such file or directory
valheim_1     | ln: failed to create symbolic link '/home/steam/.steam/steam': No such file or directory
valheim_1     | [ODIN][ERROR] - Exited with http code: 1
```

**Comment by spannerman79** [comment]
Need more info.
Provide `docker-compose.yml`, etc.

Giving a snip of a log is about as useful as tits on a bull.

If I had issue management perms I would have closed this issue as incomplete/too lazy.

**Comment by hdcola** [comment]
use https://github.com/mbround18/valheim-docker/blob/main/docker-compose.yml for start docker-compose up

**Comment by spannerman79** [comment]
@hdcola **NO!!**

Did you even bother to look at that? it is an _example_.  Not to follow character by character.
