### ISSUE TITLE
valheim-odin loop restarting

### ISSUE THREAD

**Issue by D0tty** [mbround18/valheim-docker#71]
Hi,

I think there is a problem with `valheim-odin`:

docker-compose log odin gives
```
Attaching to valheim_odin_1
odin_1     | odin 1.1.0
odin_1     | odin 1.1.0
odin_1     | odin 1.1.0
odin_1     | odin 1.1.0
odin_1     | odin 1.1.0
odin_1     | odin 1.1.0
odin_1     | odin 1.1.0
odin_1     | odin 1.1.0
odin_1     | odin 1.1.0
odin_1     | odin 1.1.0
odin_1     | odin 1.1.0
odin_1     | odin 1.1.0
odin_1     | odin 1.1.0
odin_1     | odin 1.1.0
```
docker ps gives
```
50f27a4618db   mbround18/valheim-odin:latest   "/data/odin/target/r…"   35 minutes ago   Restarting (0) 32 seconds ago valheim_odin_1
```

Is that a known behavior ?

On the other hand the server is running fine, thanks for the image, might do a PR some times in the future :)

**Comment by mbround18** [comment]
Do you have restart: always turned on?

**Comment by mbround18** [comment]
Errmm wait a minute did you copy the docker-compose inside the repo? Or from the readme? You should remove the odin service from your docker-compose

**Comment by D0tty** [comment]
> Do you have restart: always turned on?
I have a restart unless-stopped yes

> Errmm wait a minute did you copy the docker-compose inside the repo?
I cloned the repo so yeah I have the docker-compose from the repo

hum okay I guess I'll remove it then 😉

**Comment by mbround18** [comment]
Lol, maybe I should include a develop docker compose and a basic production one :P

**Comment by D0tty** [comment]
Haha yeah that should do it x)

**Comment by mbround18** [comment]
@D0tty cool if I close this?

**Comment by D0tty** [comment]
oh yeah my bad ^_^
