### ISSUE TITLE
Config from docker-compose gets ignored after automatic restart

### ISSUE THREAD

**Issue by jonaskpb** [mbround18/valheim-docker#74]
After the nightly automatic restart, the config values set in the docker-compose.yml seem to get lost in the configuration of the game server.
I set a custom game name and a password. When the server went back online following the automatic update, the game name was reset to the default value "Valheim powered by Odin" and I was not able to log in with the password I set in the compose file.

However, I was able to get it to work again by doing a `docker-compose down` followed by `docker-compose up -d`

**Comment by D0tty** [comment]
I had the same behavior but was thinking it was because of misconfiguration on my end, it seems not?

**Comment by mbround18** [comment]
I can take a look at this <3 i had issues connecting to server today as well

**Comment by D0tty** [comment]
Maybe the environment variables are lost when the cronjob is run?
I could have a look on Monday at the earliest as I will have a busy Sunday and will not be able to look at it more in depth.

But it's not a pressing issue as there is already a workaround! 😀

**Comment by mbround18** [comment]
Yeah, cron always run with an empty env. I have a pr up for it now if you wouldnt mind taking a gander? #77
