### ISSUE TITLE
Cannot connect anymore since latest update (2023-Oct-11)

### ISSUE THREAD

**Issue by cyrrelsneer** [mbround18/valheim-docker#746]
Hi,

container says "unhealthy", connection is not working anymore.
Have updated via Portainer, if that is of relevance.
Tried with and without the last modifier env.

Last output on the log front:

`10/11/2023` 08:51:58: Stopping build thread
Unloading 17 unused Assets to reduce memory usage. Loaded Objects now: 153544.
Total: 190.905261 ms (FindLiveObjects: 4.937130 ms CreateObjectMapping: 14.939483 ms MarkObjects: 170.823740 ms  DeleteObjects: 0.204532 ms)
Setting up 6 worker threads for Enlighten.
  Thread -> id: 7f6635a09640 -> priority: 1 
  Thread -> id: 7f6635208640 -> priority: 1 
  Thread -> id: 7f6634a07640 -> priority: 1 
  Thread -> id: 7f6634206640 -> priority: 1 
  Thread -> id: 7f6633a05640 -> priority: 1 
  Thread -> id: 7f6633204640 -> priority: 1 
`

**Comment by mbround18** [comment]
Is this with the latest update to the game or the container?

**Comment by cyrrelsneer** [comment]
well I have pulled the latest container (was working fine until yesterday with the 2 days old container from your last update).
I think it auto updates the game, right?

**Comment by mbround18** [comment]
@cyrrelsneer yes the auto update should be functioning, although there is a bug with it right now i havent been able to fix

**Comment by cyrrelsneer** [comment]
nope, cannot bring it back, recreated from scratch - no connection possible

**Comment by mbround18** [comment]
@cyrrelsneer i just pushed a new version, can you try https://github.com/mbround18/valheim-docker/releases/tag/v2.3.1

**Comment by cyrrelsneer** [comment]
yes it is working! didnt check the new vars yet, but at least running again. thx

**Comment by cyrrelsneer** [comment]
vars for portal etc working as well . thank you so much!
