### ISSUE TITLE
resource modifier help

### ISSUE THREAD

**Issue by Sparkdaddy** [mbround18/valheim-docker#753]
I've been trying to get the environment variable `MODIFIERS=resource=muchmore` to work on a docker-compose file but this docker file doesn't seem to be respecting that configuration. I don't see anywhere in the documentation or README.md of what value I need to get the 2x value and if it is `resource` or `resources`, etc. Can you please provide a suggestion of what the config should be?

**Comment by spannerman79** [comment]
https://www.reddit.com/r/valheim/comments/16us3ql/how_to_world_modifiers_in_game_works_on_dedicated/

**Comment by mbround18** [comment]
@Sparkdaddy are you on the latest container version? if so can you drop your start log here?

**Comment by Sparkdaddy** [comment]
whoa, y'all are on top of it! I will try `resources` tomorrow morning. Thanks @spannerman79 

> @Sparkdaddy are you on the latest container version? if so can you drop your start log here?

I have the `:latest` tag specified. And I thought with the auto-updates that I wouldn't need to redownload the docker container but there's a chance I'm wrong. I'll go try to find the metadata tomorrow as well

**Comment by mbround18** [comment]
auto updates are for the game and not the container, think of the container as an engaged process it needs to be stopped and repulled to update the code.

**Comment by mbround18** [comment]
@Sparkdaddy  can this be closed?
