### ISSUE TITLE
Requesting help,I created a container using the container,but it indicates that it is unhealthy and unable to connect.

### ISSUE THREAD

**Issue by HelIwalker** [mbround18/valheim-docker#757]
The out of sync library is: /home/steam/valheim/unstripped_corlib/mscorlib.dll
When you update one from git you need to update, compile and install
the other too.
Do not report this as a bug unless you're sure you have updated correctly:
you probably have a broken mono install.
If you see other errors or faults after this message they are probably related
and you need to fix your mono install first.
cant resolve internal call to "Mono.SafeStringMarshal::StringToUtf8(string)" (tested without signature also)
Your mono runtime and class libraries are out of sync.
The out of sync library is: /home/steam/valheim/unstripped_corlib/mscorlib.dll
When you update one from git you need to update, compile and install
the other too.
Do not report this as a bug unless you're sure you have updated correctly:
you probably have a broken mono install.
If you see other errors or faults after this message they are probably related
and you need to fix your mono install first.
cant resolve internal call to "Mono.SafeStringMarshal::StringToUtf8(string)" (tested without signature also)
Your mono runtime and class libraries are out of sync.
The out of sync library is: /home/steam/valheim/unstripped_corlib/mscorlib.dll
When you update one from git you need to update, compile and install
the other too.
Do not report this as a bug unless you're sure you have updated correctly:
you probably have a broken mono install.
If you see other errors or faults after this message they are probably related
and you need to fix your mono install first.
cant resolve internal call to "System.MissingMemberException::FormatSignature" (tested without signature also)
Your mono runtime and class libraries are out of sync.
The out of sync library is: /home/steam/valheim/unstripped_corlib/mscorlib.dll
When you update one from git you need to update, compile and install
the other too.
Do not report this as a bug unless you're sure you have updated correctly:
you probably have a broken mono install.
If you see other errors or faults after this message they are probably related
and you need to fix your mono install first.
cant resolve internal call to "System.Reflection.MemberInfo::get_MetadataToken" (tested without signature also)
Your mono runtime and class libraries are out of sync.
The out of sync library is: /home/steam/valheim/unstripped_corlib/mscorlib.dll
When you update one from git you need to update, compile and install
the other too.
Do not report this as a bug unless you're sure you have updated correctly:
you probably have a broken mono install.
If you see other errors or faults after this message they are probably related
and you need to fix your mono install first.
Caught fatal signal - signo:11 code:1 errno:0 addr:(nil)
Obtained 15 stack frames.
#0  0x007f0ce101a520 in __sigaction
#1             (nil) in (Unknown)
#2  0x00000041df0feb in (wrapper managed-to-native) Mono.SafeStringMarshal:StringToUtf8 (string)
#3  0x00000041df0f03 in Mono.SafeStringMarshal:get_Value ()
#4  0x00000041df0e43 in System.Environment:internalGetEnvironmentVariable (string)
#5  0x00000041df0dbf in System.Environment:GetEnvironmentVariable (string)
#6  0x00000041de22a3 in System.TimeZoneInfo:CreateLocal ()
#7  0x00000041de1fe7 in System.TimeZoneInfo:get_Local ()
#8  0x00000041de1f77 in System.TimeZoneInfo:GetDateTimeNowUtcOffsetFromUtc (System.DateTime,bool&)
#9  0x00000041de169b in System.DateTime:get_Now ()
#10 0x00000041de1203 in BepInEx.Preloader.Entrypoint:Main ()
#11 0x00000041de1610 in (wrapper runtime-invoke) object:runtime_invoke_void (object,intptr,intptr,intptr)
#12 0x007f0cac9e53fe in mono_runtime_invoke
#13 0x007f0caca3f70d in mono_gc_pending_finalizers
#14 0x007f0ce0775f00 in (Unknown)
[Valheim][steam]: Herding Graydwarfs...
==> /home/steam/valheim/logs/valheim_server.log <==
[ODIN][ERROR] - Error: unable to set group, errno 1
==> /home/steam/valheim/logs/valheim_server.err <==
==> /home/steam/valheim/logs/output.log <==
==> /home/steam/valheim/logs/auto-update.out <==
==> /home/steam/valheim/logs/auto-backup.out <==
[Valheim][steam]: Starting auto backup process...
[Valheim][steam]: Removing old backups...
[Valheim][steam]: Creating backup...
[Valheim][steam]: Backup process complete! Created 20231115-151501-backup.tar.gz
[Valheim][steam]: Starting auto backup process...
[Valheim][steam]: Removing old backups...
[Valheim][steam]: Creating backup...
[Valheim][steam]: Backup process complete! Created 20231115-153001-backup.tar.gz
[Valheim][steam]: Starting auto backup process...
[Valheim][steam]: Removing old backups...
[Valheim][steam]: Creating backup...
[Valheim][steam]: Backup process complete! Created 20231115-154501-backup.tar.gz
[Valheim][steam]: Starting auto backup process...
[Valheim][steam]: Removing old backups...
[Valheim][steam]: Creating backup...
[Valheim][steam]: Backup process complete! Created 20231115-160001-backup.tar.gz
[Valheim][steam]: Starting auto backup process...
[Valheim][steam]: Removing old backups...
[Valheim][steam]: Creating backup...
[Valheim][steam]: Backup process complete! Created 20231115-161501-backup.tar.gz

**Comment by mbround18** [comment]
@HelIwalker Looks like your running a modded server on an updated server, can you try removing the mods completely and starting your sever in vanilla?

**Comment by mbround18** [comment]
@HelIwalker any updates?

**Comment by mbround18** [comment]
I will be closing this issue due to its staleness
