### ISSUE TITLE
Auto-Update

### ISSUE THREAD

**Issue by Devidian** [mbround18/valheim-docker#8]
Hey man, 

first of all thanks for the docker. I was close to create my own when i found yours instead. Working fine so far but it seems there is no update call to steamcmd if the entrypoint detects the game executable. Is there any way to upgrade the server? 

I solved it in my case by completly removing the app and reinstall, of course i missed to backup my save before :D 

Greeings
Devidian

**Comment by briandilley** [comment]
If you mounted the volumes from the sample you should just be able to pull a new image right?

**Comment by mbround18** [comment]
Yes, technically speaking if you only mount the save directory you should just be able to restart the container and it should redownload files. I haven't tested this functionality yet but the logic is there.

I can add some update functionality too :) you can just rerun install to download the update but I can create some additional functions

**Comment by Devidian** [comment]
Oh i meant steamcmd should Just Check Files and Patch if possible, If you execute it at Startup. Others Steam Servers i Run do the Same. So i can Just Run docker-compile restart. Even with a mounted Game dir.

**Capital Letters Copyright by mobile correction

**Comment by mbround18** [comment]
@Devidian I removed the if check, rerunning `odin install` each start of the container will check for app updates and not force reinstalling the server.
