### ISSUE TITLE
Thunderstore API URL Change

### ISSUE THREAD

**Issue by OverkillSD** [mbround18/valheim-docker#804]
The API for Thunderstore has changed and the valheim.thunderstore.io URL is defunct.

The correct curl, per https://thunderstore.io/api/docs/, is:
curl -X GET "https://thunderstore.io/api/experimental/package/BepInExPack_Valheim/denikson/" -H  "accept: application/json" -H  "X-CSRFToken: --tokenhere--"

**Comment by Oglaf** [comment]
As a workaround, after initializing docker for the first time you can manually install BepInEx using odin.
`odin mod:install https://thunderstore.io/package/download/denikson/BepInExPack_Valheim/5.4.2202/`

**Comment by mbround18** [comment]
This still works https://gcdn.thunderstore.io/live/repository/packages/denikson-BepInExPack_Valheim-5.4.2102.zip

**Comment by mbround18** [comment]
Ahh i see

**Comment by mbround18** [comment]
https://github.com/mbround18/valheim-docker/blob/ec122553b794f21304dbc2f9ac8663baf57f0b04/src/scripts/entrypoint.sh#L72 is the issue, updating that url shortly

**Comment by mbround18** [comment]
Fixed in https://github.com/mbround18/valheim-docker/pull/807
