### ISSUE TITLE
How to run (Ashlands) beta version?

### ISSUE THREAD

**Issue by Flash1232** [mbround18/valheim-docker#838]
I would have assumed that we could just add "-beta yesimadebackups" as ADDITIONAL_STEAMCMD_ARGS but it seems the README is outdated and that env var does not exist anymore (/for now?): https://github.com/mbround18/valheim-docker/blob/79348e1c092ac0680c6d2dc88d5ec444cca7a8d2/src/odin/server/install.rs#L71

Or am I missing something?

**Comment by mbround18** [comment]
@Flash1232 `USE_PUBLIC_BETA=1`  or add them to additional vars
