### ISSUE TITLE
Backup restore documentation missing or not linked.

### ISSUE THREAD

**Issue by tmzhuang** [mbround18/valheim-docker#852]
![image](https://github.com/mbround18/valheim-docker/assets/1159725/0c58af30-1fdf-474a-b2f1-9c0e97b1ebe5)

Not too sure if linking the documentation was forgotten or it actually doesn't exist yet.

**Comment by mbround18** [comment]
https://github.com/mbround18/valheim-docker/blob/main/docs/tutorials/how-to-restore.md

**Comment by mbround18** [comment]
Good catch it was double linked https://github.com/mbround18/valheim-docker/pull/858
