### ISSUE TITLE
version mismatch on container v3

### ISSUE THREAD

**Issue by mbround18** [mbround18/valheim-docker#853]
I just started getting a version mismatch today.

It looks like in spite of `USE_PUBLIC_BETA` being set to `0` or even commented out, the server is updating to the `0.218.16` which is, as of this writing, Public Test, not an official release.

Game client is `0.218.15`

_Originally posted by @jojobyte in https://github.com/mbround18/valheim-docker/discussions/844#discussioncomment-9602122_

**Comment by jojobyte** [comment]
Not sure if its relevant or not, but in case it is, here is some added context.

My server was originally running the beta for ashlands, then when it officially released, I commented out the `USE_PUBLIC_BETA` in the `docker-compose.yml` file, with the assumption it would switch back to official release.

When I was unable to login a few days ago and got the version mismatch error in valheim, I could see my game client is still on official and went through the server logs to see it is on the PTR `0.218.16`.

I then brought down the server, uncommented & set `USE_PUBLIC_BETA: 0` in `docker-compose.yml` and brought it back up.

The compose file also has `UPDATE_ON_STARTUP: 1`, that said the server would not download the `0.218.15` version.

Which has me speculating either it will only update to higher number versions or theres some lingering change from the beta flag thats making it want to stay on the beta branch.

**Comment by mbround18** [comment]
You have to blow away the server directory if you switch back, unfortunately if you go from beta to standard I dont have a route to downgrade in code

**Comment by mbround18** [comment]
Any updates @jojobyte
