### ISSUE TITLE
Random Issue

### ISSUE THREAD

**Issue by Thunder1723** [mbround18/valheim-docker#906]
I can't make sense of this log and I am not sure where the actual problem is because as far as I'm aware it whining about my gpu shouldn't matter.

Compose for reference, mods are commented out because until I can figure out whatever is going on I'm not messing with them
```
version: "3"
services:
  valheim:
    image: mbround18/valheim:latest
    stop_signal: SIGINT
    ports:
      - "2456:2456/udp"
    environment:
      PORT: 2456
      NAME: ""
      WORLD: ""
      PASSWORD: ""
      TZ: "America/Chicago"
      PUBLIC: 0
      AUTO_UPDATE: 1
      AUTO_UPDATE_SCHEDULE: "0 4 * * *"
      AUTO_BACKUP: 1
      AUTO_BACKUP_SCHEDULE: "0 * * * *"
      AUTO_BACKUP_REMOVE_OLD: 1
      AUTO_BACKUP_DAYS_TO_LIVE: 3
      AUTO_BACKUP_ON_UPDATE: 1
      AUTO_BACKUP_ON_SHUTDOWN: 1
      UPDATE_ON_STARTUP: 0
      TYPE: BepInEx
      #MODS: "
        #https://thunderstore.io/package/download/TastyChickenLegs/NoSmokeSimplified/1.0.8/
        #https://thunderstore.io/package/download/WiseHorror/Veinmine/1.3.0/
        #https://thunderstore.io/package/download/Advize/PlantEverything/1.18.1/
        #https://thunderstore.io/package/download/ishid4/BetterArchery/1.9.7/
        #https://thunderstore.io/package/download/blacks7ar/LazyVikings/1.1.5/
        #https://thunderstore.io/package/download/Azumatt/PetPantry/1.0.2/
       # "
    volumes:
      - /Valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
      - /Valheim/server:/home/steam/valheim
      - /Valheim/backups:/home/steam/backups
```

[ODIN][INFO]: [valheim_server.log]: [Info   :   BepInEx] Supports SRE: True
[ODIN][INFO]: [valheim_server.log]: [Info   :   BepInEx] System platform: Bits64, Linux
[ODIN][INFO]: [valheim_server.log]: [Message:   BepInEx] Preloader started
[ODIN][INFO]: [valheim_server.log]: [Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[ODIN][INFO]: [valheim_server.log]: [Info   :   BepInEx] 1 patcher plugin loaded
[ODIN][INFO]: [valheim_server.log]: [Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[ODIN][INFO]: [valheim_server.log]: [Message:   BepInEx] Preloader finished
[ODIN][INFO]: [valheim_server.log]: [Info   :   BepInEx] Detected Unity version: v2020.3.45f1
[ODIN][INFO]: [valheim_server.log]: [Message:   BepInEx] Chainloader ready
[ODIN][INFO]: [valheim_server.log]: [Message:   BepInEx] Chainloader started
[ODIN][INFO]: [valheim_server.log]: [Info   :   BepInEx] 2 plugins to load
[ODIN][INFO]: [valheim_server.log]: [Warning:   BepInEx] Skipping [Display BepInEx Info In-Game 2.0.1] because a newer version exists (Display BepInEx Info In-Game 2.0.2)
[ODIN][INFO]: [valheim_server.log]: [Info   :   BepInEx] Loading [Display BepInEx Info In-Game 2.0.2]
[ODIN][INFO]: [valheim_server.log]: Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/mscorlib/mono/aot-cache/amd64/Valheim.DisplayBepInExInfo.dll.so
[ODIN][INFO]: [valheim_server.log]: Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/mscorlib/mono/aot-cache/amd64/Valheim.DisplayBepInExInfo.dll.so
[ODIN][INFO]: [valheim_server.log]: Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/data-0x5b23228c7d00.so
[ODIN][INFO]: [valheim_server.log]: Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/mscorlib/mono/aot-cache/amd64/data-0x5b23228c7d00.so
[ODIN][INFO]: [valheim_server.log]: Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/data-0x5b2323fbf5c0.so
[ODIN][INFO]: [valheim_server.log]: Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/mscorlib/mono/aot-cache/amd64/data-0x5b2323fbf5c0.so
[ODIN][INFO]: [valheim_server.log]: Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/data-0x5b2323fe53d0.so
[ODIN][INFO]: [valheim_server.log]: Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/mscorlib/mono/aot-cache/amd64/data-0x5b2323fe53d0.so
[ODIN][INFO]: [valheim_server.log]: Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/data-0x5b2324001a60.so
[ODIN][INFO]: [valheim_server.log]: Fallback handler could not load library /home/steam/valheim/valheim_server_Data/Mono/mscorlib/mono/aot-cache/amd64/data-0x5b2324001a60.so
[ODIN][INFO]: [valheim_server.log]: [Message:   BepInEx] Chainloader startup complete
[ODIN][INFO]: [valheim_server.log]: 07/30/2024 19:28:27: Starting to load scene:start
[ODIN][ERROR]: [valheim_server.log]: ERROR: Shader UI/Default shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
[ODIN][INFO]: [valheim_server.log]: Couldn't create a Convex Mesh from source mesh "default" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
[ODIN][INFO]: [valheim_server.log]: Couldn't create a Convex Mesh from source mesh "default" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
[ODIN][ERROR]: [valheim_server.log]: ERROR: Shader Legacy Shaders/VertexLit shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader Unsupported: 'Standard (Specular setup)' - All subshaders removed
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader Did you use #pragma only_renderers and omit this platform?
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
[ODIN][ERROR]: [valheim_server.log]: ERROR: Shader Standard (Specular setup) shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader Unsupported: 'Standard (Specular setup)' - All subshaders removed
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader Did you use #pragma only_renderers and omit this platform?
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader Unsupported: 'Standard' - All subshaders removed
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader Did you use #pragma only_renderers and omit this platform?
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
[ODIN][ERROR]: [valheim_server.log]: ERROR: Shader Standard shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader Unsupported: 'Standard' - All subshaders removed
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader Did you use #pragma only_renderers and omit this platform?
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader Unsupported: 'Autodesk Interactive' - All subshaders removed
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader Did you use #pragma only_renderers and omit this platform?
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
[ODIN][ERROR]: [valheim_server.log]: ERROR: Shader Autodesk Interactive shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader Unsupported: 'Autodesk Interactive' - All subshaders removed
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader Did you use #pragma only_renderers and omit this platform?
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
[ODIN][ERROR]: [valheim_server.log]: ERROR: Shader Legacy Shaders/Particles/Additive shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
[ODIN][ERROR]: [valheim_server.log]: ERROR: Shader Legacy Shaders/Particles/Alpha Blended shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
[ODIN][ERROR]: [valheim_server.log]: ERROR: Shader Legacy Shaders/Particles/Alpha Blended Premultiply shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
[ODIN][ERROR]: [valheim_server.log]: ERROR: Shader Unlit/Color shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
[ODIN][ERROR]: [valheim_server.log]: ERROR: Shader Lux Lit Particles/ Bumped shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
[ODIN][INFO]: [valheim_server.log]: Shader 'Lux Lit Particles/ Tess Bumped': fallback shader 'Lux Lit Particles/ Bumped Smoke' not found
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader Unsupported: 'Lux Lit Particles/ Tess Bumped' - All subshaders removed
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader Did you use #pragma only_renderers and omit this platform?
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
[ODIN][ERROR]: [valheim_server.log]: ERROR: Shader Lux Lit Particles/ Tess Bumped shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader Unsupported: 'Lux Lit Particles/ Tess Bumped' - All subshaders removed
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader Did you use #pragma only_renderers and omit this platform?
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
[ODIN][ERROR]: [valheim_server.log]: ERROR: Shader TextMeshPro/Distance Field (Surface) shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
[ODIN][ERROR]: [valheim_server.log]: ERROR: Shader TextMeshPro/Mobile/Distance Field shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader Unsupported: 'TextMeshPro/Distance Field' - All subshaders removed
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader Did you use #pragma only_renderers and omit this platform?
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
[ODIN][ERROR]: [valheim_server.log]: ERROR: Shader TextMeshPro/Distance Field shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader Unsupported: 'TextMeshPro/Distance Field' - All subshaders removed
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader Did you use #pragma only_renderers and omit this platform?
[ODIN][WARN]: [valheim_server.log]: WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?
[ODIN][INFO]: [valheim_server.err]: [S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
[ODIN][INFO]: [valheim_server.err]: CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
[ODIN][INFO]: [valheim_server.log]: Unloading 6 Unused Serialized files (Serialized files now loaded: 0)
[ODIN][INFO]: [valheim_server.log]: UnloadTime: 3.975842 ms
[ODIN][INFO]: [valheim_server.log]: Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Amb_MainMenu).
[ODIN][INFO]: [valheim_server.log]: HDR Render Texture not supported, disabling HDR on reflection probe.
[ODIN][INFO]: [valheim_server.log]: 07/30/2024 19:28:28: Setting -savedir to: /home/steam/.config/unity3d/IronGate/Valheim
[ODIN][INFO]: [valheim_server.log]: 07/30/2024 19:28:28: Get create world 
[ODIN][INFO]: [valheim_server.log]: 07/30/2024 19:28:28: Using environment steamid 
[ODIN][INFO]: [valheim_server.log]: 07/30/2024 19:28:28: Using steam APPID:
[ODIN][INFO]: [valheim_server.err]: Setting breakpad minidump AppID = 
[ODIN][INFO]: [valheim_server.err]: [S_API FAIL] Tried to access Steam interface SteamNetworkingUtils003 before SteamAPI_Init succeeded.
[ODIN][INFO]: [valheim_server.log]: 07/30/2024 19:28:28: Server ID
[ODIN][INFO]: [valheim_server.log]: 07/30/2024 19:28:28: Authentication:k_ESteamNetworkingAvailability_Waiting
[ODIN][INFO]: [valheim_server.log]: 07/30/2024 19:28:28: Steam game server initialized
[ODIN][INFO]: [valheim_server.log]: 07/30/2024 19:28:28: Using default prefs
[ODIN][INFO]: [valheim_server.log]: 07/30/2024 19:28:28: Valheim version: 0.215.2 (network version 1)
[ODIN][INFO]: [valheim_server.log]: 07/30/2024 19:28:28: Worldgenerator version setup:2
[ODIN][ERROR]: [valheim_server.log]: ERROR: Shader TextMeshPro/Sprite shader is not supported on this GPU (none of subshaders/fallbacks are suitable)
[ODIN][INFO]: [valheim_server.log]: 07/30/2024 19:28:28: Render threading mode:SingleThreaded
[ODIN][INFO]: [valheim_server.log]: 07/30/2024 19:28:28: Missing audio clip in music respawn
[ODIN][INFO]: [valheim_server.log]: 07/30/2024 19:28:29: Builder started
[ODIN][INFO]: [valheim_server.log]: GetPixel called on an undefined mip (valid values are 0 - 6
[ODIN][INFO]: [valheim_server.log]: Caught fatal signal - signo:11 code:1 errno:0 addr:0x3fb
[ODIN][INFO]: [valheim_server.log]: Obtained 3 stack frames.
[ODIN][INFO]: [valheim_server.log]: #0  0x007043a5642520 in __sigaction
[ODIN][INFO]: [valheim_server.log]: #1  0x007043a69792c3 in Texture2D_CUSTOM_GetPixelImpl_Injected(ScriptingBackendNativeObjectPtrOpaque*, int, int, int, int, ColorRGBAf&)
[ODIN][INFO]: [valheim_server.log]: #2  0x00000040722eb5 in (wrapper managed-to-native) UnityEngine.Texture2D:GetPixelImpl_Injected (UnityEngine.Texture2D,int,int,int,UnityEngine.Color&)_

**Comment by mbround18** [comment]
thats an issue witth a mod, my suggestion is slowly delete a one mod at a time and keep retrying

**Comment by mbround18** [comment]
Stale issue, closing
